insert into crew (Cid, Name, Location) values (1, 'The Black Tide', 'Bloodwake Bay');
insert into crew (Cid, Name, Location) values (2, 'Crimson Corsairs', 'Siren’s Cove');
insert into crew (Cid, Name, Location) values (3, 'The Daggerfangs', 'Dead Man’s Strait');
insert into crew (Cid, Name, Location) values (4, 'Bone Reef Marauders', 'Blackreef Lagoon');
insert into crew (Cid, Name, Location) values (5, 'The Storm Serpents', 'Leviathan’s Grave');
insert into crew (Cid, Name, Location) values (6, 'Ironfang Buccaneers', 'Whispering Tides');
insert into crew (Cid, Name, Location) values (7, 'The Scarlet Wraiths', 'Daggerjaw Shoals');
insert into crew (Cid, Name, Location) values (8, 'Drowned Ghosts', 'The Drowned Isles');
insert into crew (Cid, Name, Location) values (9, 'The Siren’s Howl', 'Stormwreck Atoll');
insert into crew (Cid, Name, Location) values (10, 'Bloodwake Raiders', 'Broken Mast Bay');
insert into crew (Cid, Name, Location) values (11, 'The Ashen Blades', 'Grimwater Sound');
insert into crew (Cid, Name, Location) values (12, 'Leviathan’s Bane', 'Devil’s Backbone Reef');
insert into crew (Cid, Name, Location) values (13, 'The Rusted Cutlasses', 'Rusted Anchor Haven');
insert into crew (Cid, Name, Location) values (14, 'Grimwater Gang', 'Phantom Shoals');
insert into crew (Cid, Name, Location) values (15, 'The Broken Compass', 'Hollowwave Gulf');
insert into crew (Cid, Name, Location) values (16, 'Cursed Horizon', 'The Cursed Channels');
insert into crew (Cid, Name, Location) values (17, 'The Silver Scourge', 'Ashen Depths');
insert into crew (Cid, Name, Location) values (18, 'Dead Man’s Grin', 'Shattered Compass Key');
insert into crew (Cid, Name, Location) values (19, 'The Voodoo Vultures', 'Skeleton Cove');
insert into crew (Cid, Name, Location) values (20, 'Salty Revenants', 'Shadowmist Isle');
insert into crew (Cid, Name, Location) values (21, 'Howling Skulls', 'Wraithwater Bay');
insert into crew (Cid, Name, Location) values (22, 'The Golden Kraken', 'Frostbite Strait');
insert into crew (Cid, Name, Location) values (23, 'Widowmakers of the Deep', 'Coralgrave Lagoon');
insert into crew (Cid, Name, Location) values (24, 'The Barnacle Brotherhood', 'Shipwreck Shoals');
insert into crew (Cid, Name, Location) values (25, 'Black Powder Pact', 'Bonefire Cay');
insert into crew (Cid, Name, Location) values (26, 'The Phantom Corsairs', 'Twilight Tides');
insert into crew (Cid, Name, Location) values (27, 'Coralblade Clan', 'Abyssal Maw Trench');
insert into crew (Cid, Name, Location) values (28, 'The Raging Tempest', 'Gallowglass Gulf');
insert into crew (Cid, Name, Location) values (29, 'Shattered Mast Marauders', 'Shrouded Reef');
insert into crew (Cid, Name, Location) values (30, 'The Crimson Albatross', 'Ironwake Harbor.');
insert into crew (Cid, Name, Location) values (31, 'Devil’s Backbone', 'Bloodwake Bay');
insert into crew (Cid, Name, Location) values (32, 'The Daggered Sirens', 'Siren’s Cove');
insert into crew (Cid, Name, Location) values (33, 'The Bitter Enders', 'Dead Man’s Strait');
insert into crew (Cid, Name, Location) values (34, 'No Quarter Company', 'Blackreef Lagoon');
insert into crew (Cid, Name, Location) values (35, 'The Tempest Wolves', 'Leviathan’s Grave');
insert into crew (Cid, Name, Location) values (36, 'Bloodmoon Marauders', 'Whispering Tides');
insert into crew (Cid, Name, Location) values (37, 'The Fathomless Few', 'Daggerjaw Shoals');
insert into crew (Cid, Name, Location) values (38, 'Gravedigger’s Crew', 'The Drowned Isles');
insert into crew (Cid, Name, Location) values (39, 'The Sunken Daggers', 'Stormwreck Atoll');
insert into crew (Cid, Name, Location) values (40, 'The Hollow Jollys', 'Broken Mast Bay');
insert into crew (Cid, Name, Location) values (41, 'Iron Anchor Alliance', 'Grimwater Sound');
insert into crew (Cid, Name, Location) values (42, 'Ghostwake Company', 'Devil’s Backbone Reef');
insert into crew (Cid, Name, Location) values (43, 'Blackfin Buccaneers', 'Rusted Anchor Haven');
insert into crew (Cid, Name, Location) values (44, 'The Shadowbound', 'Phantom Shoals');
insert into crew (Cid, Name, Location) values (45, 'The Maelstrom Men', 'Hollowwave Gulf');
insert into crew (Cid, Name, Location) values (46, 'Deadwater Drifters', 'The Cursed Channels');
insert into crew (Cid, Name, Location) values (47, 'The Twisted Compass', 'Ashen Depths');
insert into crew (Cid, Name, Location) values (48, 'Sable Corsairs', 'Shattered Compass Key');
insert into crew (Cid, Name, Location) values (49, 'The Brineborn', 'Skeleton Cove');
insert into crew (Cid, Name, Location) values (50, 'The Gallows Gulls', 'Shadowmist Isle');
insert into crew (Cid, Name, Location) values (51, 'Rustskull Raiders', 'Wraithwater Bay');
insert into crew (Cid, Name, Location) values (52, 'The Scourged Sails', 'Frostbite Strait');
insert into crew (Cid, Name, Location) values (53, 'The Midnight Corsairs', 'Coralgrave Lagoon');
insert into crew (Cid, Name, Location) values (54, 'The Bone Rats', 'Shipwreck Shoals');
insert into crew (Cid, Name, Location) values (55, 'Blood Reef Brotherhood', 'Bonefire Cay');
insert into crew (Cid, Name, Location) values (56, 'The Silent Maelstrom', 'Twilight Tides');
insert into crew (Cid, Name, Location) values (57, 'The Wretched Tide', 'Abyssal Maw Trench');
insert into crew (Cid, Name, Location) values (58, 'The Sunken Scepters', 'Gallowglass Gulf');
insert into crew (Cid, Name, Location) values (59, 'The Reefcursed', 'Shrouded Reef');
insert into crew (Cid, Name, Location) values (60, 'Black Reef Revenants', 'Ironwake Harbor.');
insert into crew (Cid, Name, Location) values (61, 'The Coral Crows', 'Bloodwake Bay');
insert into crew (Cid, Name, Location) values (62, 'The Howling Horizon', 'Siren’s Cove');
insert into crew (Cid, Name, Location) values (63, 'The Pale Cutlasses', 'Dead Man’s Strait');
insert into crew (Cid, Name, Location) values (64, 'Redwater Marauders', 'Blackreef Lagoon');
insert into crew (Cid, Name, Location) values (65, 'The Sea Scourge', 'Leviathan’s Grave');
insert into crew (Cid, Name, Location) values (66, 'Grimflag Corsairs', 'Whispering Tides');
insert into crew (Cid, Name, Location) values (67, 'The Abyssal Blades', 'Daggerjaw Shoals');
insert into crew (Cid, Name, Location) values (68, 'The Iron Reavers', 'The Drowned Isles');
insert into crew (Cid, Name, Location) values (69, 'Shipwreck Saints', 'Stormwreck Atoll');
insert into crew (Cid, Name, Location) values (70, 'Plaguewake Crew', 'Broken Mast Bay');
insert into crew (Cid, Name, Location) values (71, 'The Shrouded Dagger', 'Grimwater Sound');
insert into crew (Cid, Name, Location) values (72, 'Lanternjaw Buccaneers', 'Devil’s Backbone Reef');
insert into crew (Cid, Name, Location) values (73, 'The Ashen Kraken', 'Rusted Anchor Haven');
insert into crew (Cid, Name, Location) values (74, 'Broken Anchor Brotherhood', 'Phantom Shoals');
insert into crew (Cid, Name, Location) values (75, 'The Damned Dagger', 'Hollowwave Gulf');
insert into crew (Cid, Name, Location) values (76, 'The Saltborn Scoundrels', 'The Cursed Channels');
insert into crew (Cid, Name, Location) values (77, 'Frostwake Fleet', 'Ashen Depths');
insert into crew (Cid, Name, Location) values (78, 'Death’s Toll', 'Shattered Compass Key');
insert into crew (Cid, Name, Location) values (79, 'Saltfang Buccaneers', 'Skeleton Cove');
insert into crew (Cid, Name, Location) values (80, 'The Grimcurrent', 'Shadowmist Isle');
insert into crew (Cid, Name, Location) values (81, 'The Jaded Compass', 'Wraithwater Bay');
insert into crew (Cid, Name, Location) values (82, 'Deadlight Corsairs', 'Frostbite Strait');
insert into crew (Cid, Name, Location) values (83, 'Cracked Skull Marauders', 'Coralgrave Lagoon');
insert into crew (Cid, Name, Location) values (84, 'The Endless Wreck', 'Shipwreck Shoals');
insert into crew (Cid, Name, Location) values (85, 'Bloodsalt Brotherhood', 'Bonefire Cay');
insert into crew (Cid, Name, Location) values (86, 'The Gutter Sharks', 'Twilight Tides');
insert into crew (Cid, Name, Location) values (87, 'Black Coral Corsairs', 'Abyssal Maw Trench');
insert into crew (Cid, Name, Location) values (88, 'The Graveborn', 'Gallowglass Gulf');
insert into crew (Cid, Name, Location) values (89, 'Silverwave Pirates', 'Shrouded Reef');
insert into crew (Cid, Name, Location) values (90, 'The Firewater Gang', 'Ironwake Harbor.');
insert into crew (Cid, Name, Location) values (91, 'Crimson Reef Company', 'Bloodwake Bay');
insert into crew (Cid, Name, Location) values (92, 'Thunderjaw Corsairs', 'Siren’s Cove');
insert into crew (Cid, Name, Location) values (93, 'The Sunken Crossbones', 'Dead Man’s Strait');
insert into crew (Cid, Name, Location) values (94, 'Devil’s Moor Marauders', 'Blackreef Lagoon');
insert into crew (Cid, Name, Location) values (95, 'Red Tide Raiders', 'Leviathan’s Grave');
insert into crew (Cid, Name, Location) values (96, 'Broken Skull Buccaneers', 'Whispering Tides');
insert into crew (Cid, Name, Location) values (97, 'The Bleeding Horizon', 'Daggerjaw Shoals');
insert into crew (Cid, Name, Location) values (98, 'Serpent’s Wake', 'The Drowned Isles');
insert into crew (Cid, Name, Location) values (99, 'Ebonwake Company', 'Stormwreck Atoll');
insert into crew (Cid, Name, Location) values (100, 'The Shackled Souls', 'Broken Mast Bay');
