insert into island (Iid, Name, Location) values (1, 'Shadow Isle', 'Broken Mast Bay');
insert into island (Iid, Name, Location) values (2, 'Bloodstone Island', 'Hollowwave Gulf');
insert into island (Iid, Name, Location) values (3, 'The Whispering Key', 'Leviathan’s Grave');
insert into island (Iid, Name, Location) values (4, 'Skull Island', 'Devil’s Backbone Reef');
insert into island (Iid, Name, Location) values (5, 'Siren’s Rest', 'Stormwreck Atoll');
insert into island (Iid, Name, Location) values (6, 'The Black Shore', 'Frostbite Strait');
insert into island (Iid, Name, Location) values (7, 'Stormhaven Isle', 'Frostbite Strait');
insert into island (Iid, Name, Location) values (8, 'Broken Helm Isle', 'Devil’s Backbone Reef');
insert into island (Iid, Name, Location) values (9, 'Lost Reef Island', 'Ashen Depths');
insert into island (Iid, Name, Location) values (10, 'The Silent Archipelago', 'Wraithwater Bay');
insert into island (Iid, Name, Location) values (11, 'Coral Haven', 'Shattered Compass Key');
insert into island (Iid, Name, Location) values (12, 'Darkwater Cay', 'Broken Mast Bay');
insert into island (Iid, Name, Location) values (13, 'Dragon’s Claw Isle', 'Gallowglass Gulf');
insert into island (Iid, Name, Location) values (14, 'Ironhold Isle', 'Twilight Tides');
insert into island (Iid, Name, Location) values (15, 'The Cursed Isle', 'The Drowned Isles');
insert into island (Iid, Name, Location) values (16, 'The Sunken Crown', 'Ashen Depths');
insert into island (Iid, Name, Location) values (17, 'Kraken’s Nest', 'Daggerjaw Shoals');
insert into island (Iid, Name, Location) values (18, 'The Fogbound Isle', 'Frostbite Strait');
insert into island (Iid, Name, Location) values (19, 'Grimstone Island', 'Stormwreck Atoll');
insert into island (Iid, Name, Location) values (20, 'Deadman’s Bay', 'Shipwreck Shoals');
insert into island (Iid, Name, Location) values (21, 'Mistveil Isle', 'Dead Man’s Strait');
insert into island (Iid, Name, Location) values (22, 'The Forgotten Cay', 'Blackreef Lagoon');
insert into island (Iid, Name, Location) values (23, 'Phantom Isle', 'Devil’s Backbone Reef');
insert into island (Iid, Name, Location) values (24, 'Thunderclap Island', 'Whispering Tides');
insert into island (Iid, Name, Location) values (25, 'The Sable Isle', 'Gallowglass Gulf');
insert into island (Iid, Name, Location) values (26, 'The Shattered Key', 'Stormwreck Atoll');
insert into island (Iid, Name, Location) values (27, 'Widow’s Isle', 'Shadowmist Isle');
insert into island (Iid, Name, Location) values (28, 'The Ebon Island', 'The Cursed Channels');
insert into island (Iid, Name, Location) values (29, 'Moonlit Isle', 'Bonefire Cay');
insert into island (Iid, Name, Location) values (30, 'The Emerald Shore', 'Coralgrave Lagoon');
insert into island (Iid, Name, Location) values (31, 'The Ashen Island', 'Skeleton Cove');
insert into island (Iid, Name, Location) values (32, 'Scorpion Isle', 'Siren’s Cove');
insert into island (Iid, Name, Location) values (33, 'The Drowned Isles', 'Leviathan’s Grave');
insert into island (Iid, Name, Location) values (34, 'The Bitter Isle', 'Shrouded Reef');
insert into island (Iid, Name, Location) values (35, 'Bleakwater Isle', 'The Drowned Isles');
insert into island (Iid, Name, Location) values (36, 'Tempest Isle', 'Phantom Shoals');
insert into island (Iid, Name, Location) values (37, 'The Lost Archipelago', 'Gallowglass Gulf');
insert into island (Iid, Name, Location) values (38, 'The Vengeful Isle', 'Leviathan’s Grave');
insert into island (Iid, Name, Location) values (39, 'Gloomshroud Isle', 'Stormwreck Atoll');
insert into island (Iid, Name, Location) values (40, 'The Darkened Reef', 'Broken Mast Bay');
insert into island (Iid, Name, Location) values (41, 'Saltbreeze Isle', 'Ironwake Harbor.');
insert into island (Iid, Name, Location) values (42, 'The Fanged Isle', 'Shattered Compass Key');
insert into island (Iid, Name, Location) values (43, 'The Iron Coast', 'Hollowwave Gulf');
insert into island (Iid, Name, Location) values (44, 'The Forsaken Isle', 'Blackreef Lagoon');
insert into island (Iid, Name, Location) values (45, 'Skullcap Isle', 'Bonefire Cay');
insert into island (Iid, Name, Location) values (46, 'The Tidal Bastion', 'Siren’s Cove');
insert into island (Iid, Name, Location) values (47, 'Riptide Reef', 'Coralgrave Lagoon');
insert into island (Iid, Name, Location) values (48, 'Stormshadow Island', 'Bloodwake Bay');
insert into island (Iid, Name, Location) values (49, 'The Hallowed Isles', 'Whispering Tides');
insert into island (Iid, Name, Location) values (50, 'Blackwater Cove', 'Shipwreck Shoals');
insert into island (Iid, Name, Location) values (51, 'The Abyssal Island', 'Whispering Tides');
insert into island (Iid, Name, Location) values (52, 'The Wraith Isle', 'Siren’s Cove');
insert into island (Iid, Name, Location) values (53, 'Blight Isle', 'Daggerjaw Shoals');
insert into island (Iid, Name, Location) values (54, 'The Hollow Reef', 'Coralgrave Lagoon');
insert into island (Iid, Name, Location) values (55, 'Thunder Isle', 'Skeleton Cove');
insert into island (Iid, Name, Location) values (56, 'Frostbite Island', 'Bloodwake Bay');
insert into island (Iid, Name, Location) values (57, 'The Forgotten Shore', 'Shrouded Reef');
insert into island (Iid, Name, Location) values (58, 'The Flameclaw Isle', 'Rusted Anchor Haven');
insert into island (Iid, Name, Location) values (59, 'Bloodreef Island', 'Hollowwave Gulf');
insert into island (Iid, Name, Location) values (60, 'The Wrath Isle', 'Dead Man’s Strait');
insert into island (Iid, Name, Location) values (61, 'Sea Witch Isle', 'Wraithwater Bay');
insert into island (Iid, Name, Location) values (62, 'The Grim Isle', 'The Drowned Isles');
insert into island (Iid, Name, Location) values (63, 'The Phantom Reef', 'Siren’s Cove');
insert into island (Iid, Name, Location) values (64, 'Whitecliff Isle', 'Rusted Anchor Haven');
insert into island (Iid, Name, Location) values (65, 'The Voodoo Isle', 'Shipwreck Shoals');
insert into island (Iid, Name, Location) values (66, 'Ghostwind Isle', 'Grimwater Sound');
insert into island (Iid, Name, Location) values (67, 'The Chasm Isle', 'Dead Man’s Strait');
insert into island (Iid, Name, Location) values (68, 'The Spire Isle', 'The Drowned Isles');
insert into island (Iid, Name, Location) values (69, 'Ironclad Isle', 'Ironwake Harbor.');
insert into island (Iid, Name, Location) values (70, 'Bonebreaker Island', 'Twilight Tides');
insert into island (Iid, Name, Location) values (71, 'Lost Harbor Isle', 'Wraithwater Bay');
insert into island (Iid, Name, Location) values (72, 'The Scourge Isle', 'Dead Man’s Strait');
insert into island (Iid, Name, Location) values (73, 'Darkrift Isle', 'Grimwater Sound');
insert into island (Iid, Name, Location) values (74, 'Misty Haven', 'Abyssal Maw Trench');
insert into island (Iid, Name, Location) values (75, 'The Sea Serpent’s Nest', 'Bloodwake Bay');
insert into island (Iid, Name, Location) values (76, 'The Blackstone Isle', 'Bloodwake Bay');
insert into island (Iid, Name, Location) values (77, 'The Roaring Isle', 'Blackreef Lagoon');
insert into island (Iid, Name, Location) values (78, 'Saltgrave Isle', 'Shadowmist Isle');
insert into island (Iid, Name, Location) values (79, 'The Coral Tomb', 'Phantom Shoals');
insert into island (Iid, Name, Location) values (80, 'Serpent’s Spine Isle', 'Phantom Shoals');
insert into island (Iid, Name, Location) values (81, 'Sharkfang Isle', 'Daggerjaw Shoals');
insert into island (Iid, Name, Location) values (82, 'The Crimson Reef', 'Grimwater Sound');
insert into island (Iid, Name, Location) values (83, 'Wolf’s Eye Isle', 'Ironwake Harbor.');
insert into island (Iid, Name, Location) values (84, 'The Starless Isle', 'The Cursed Channels');
insert into island (Iid, Name, Location) values (85, 'The Smuggler’s Isle', 'Whispering Tides');
insert into island (Iid, Name, Location) values (86, 'The Forgotten Passage', 'Broken Mast Bay');
insert into island (Iid, Name, Location) values (87, 'Blackflame Isle', 'Leviathan’s Grave');
insert into island (Iid, Name, Location) values (88, 'The Sunken Key', 'Shattered Compass Key');
insert into island (Iid, Name, Location) values (89, 'The Razor Isle', 'Shadowmist Isle');
insert into island (Iid, Name, Location) values (90, 'The Graveyard Reef', 'Rusted Anchor Haven');
insert into island (Iid, Name, Location) values (91, 'The Eternal Isle', 'Ashen Depths');
insert into island (Iid, Name, Location) values (92, 'The Specter’s Isle', 'Abyssal Maw Trench');
insert into island (Iid, Name, Location) values (93, 'Flameheart Island', 'Daggerjaw Shoals');
insert into island (Iid, Name, Location) values (94, 'The Devil’s Cove', 'The Cursed Channels');
insert into island (Iid, Name, Location) values (95, 'Ghostfire Island', 'Shrouded Reef');
insert into island (Iid, Name, Location) values (96, 'The Wailing Isle', 'Skeleton Cove');
insert into island (Iid, Name, Location) values (97, 'The Windward Isle', 'Twilight Tides');
insert into island (Iid, Name, Location) values (98, 'Dragon’s Lair Island', 'Blackreef Lagoon');
insert into island (Iid, Name, Location) values (99, 'The Maw Isle', 'Abyssal Maw Trench');
