-- CREATE DATABASE PirateDB;
USE PirateDB;

CREATE TABLE Crew (
	Cid SMALLINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE,
    Location VARCHAR(50)
);

CREATE TABLE Ship (
    Sid MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Cid SMALLINT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Type VARCHAR(50) NOT NULL,
    
    FOREIGN KEY (Cid) REFERENCES Crew(Cid)
);

CREATE TABLE Pirate (
    Pid MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(50) NOT NULL,
    Alias VARCHAR(50),
    Age TINYINT,
    NetWorth INT NOT NULL,
    Role VARCHAR(25),
    
    Cid SMALLINT NOT NULL,
    Sid MEDIUMINT NOT NULL,
    
    FOREIGN KEY (Cid) REFERENCES Crew(Cid),
    FOREIGN KEY (Sid) REFERENCES Ship(Sid)
);

CREATE TABLE Island (
    Iid MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Location VARCHAR(50)
);

CREATE TABLE Treasure (
    Tid MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Value VARCHAR(50) NOT NULL,
    Location VARCHAR(50) NOT NULL,
    
    Iid MEDIUMINT NOT NULL,
    Pid MEDIUMINT NOT NULL,
    
    FOREIGN KEY (Iid) REFERENCES Island(Iid),
    FOREIGN KEY (Pid) REFERENCES Pirate(Pid)
);

CREATE TABLE Battle (
    Bid MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Casualties SMALLINT NOT NULL,
    Winner VARCHAR(50) NOT NULL,
    Name VARCHAR(50),
    LootAmount INT NOT NULL,
    Location VARCHAR(50) NOT NULL,
    Date DATE NOT NULL
);

CREATE TABLE Participate (
    Bid MEDIUMINT NOT NULL,
    Sid MEDIUMINT NOT NULL,
    WasSunk BOOL,
    
    PRIMARY KEY(Sid, Bid)
);

CREATE TABLE Visit (
    Iid MEDIUMINT NOT NULL,
    Sid MEDIUMINT NOT NULL,
    Date DATE,
    
    FOREIGN KEY (Iid) REFERENCES Island(Iid),
    FOREIGN KEY (Sid) REFERENCES Ship(Sid),
    
    PRIMARY KEY(Sid, Iid, Date)
);