insert into ship (Sid, Name, Type) values (1, 'Devil’s Lantern', 'Galleon');
insert into ship (Sid, Name, Type) values (2, 'Tidemourn', 'Frigate');
insert into ship (Sid, Name, Type) values (3, 'Burning Marlin', 'Sloop');
insert into ship (Sid, Name, Type) values (4, 'Hollow Warden', 'Sloop');
insert into ship (Sid, Name, Type) values (5, 'Dragon''s Maw', 'Barque');
insert into ship (Sid, Name, Type) values (6, 'Devil’s Mistress', 'Frigate');
insert into ship (Sid, Name, Type) values (7, 'Death''s Embrace', 'Barque');
insert into ship (Sid, Name, Type) values (8, 'Black Reef Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (9, 'Black Sail’s Oath', 'Barque');
insert into ship (Sid, Name, Type) values (10, 'The Ashen Revenant', 'Frigate');
insert into ship (Sid, Name, Type) values (11, 'Broken Wing', 'Galleon');
insert into ship (Sid, Name, Type) values (12, 'Darkmoon Marauder', 'Frigate');
insert into ship (Sid, Name, Type) values (13, 'Sable Wraith', 'Brigantine');
insert into ship (Sid, Name, Type) values (14, 'Devil’s Mistress', 'Brigantine');
insert into ship (Sid, Name, Type) values (15, 'Coral Reaper', 'Brigantine');
insert into ship (Sid, Name, Type) values (16, 'Bonegale', 'Barque');
insert into ship (Sid, Name, Type) values (17, 'Redwake', 'Frigate');
insert into ship (Sid, Name, Type) values (18, 'Darkwater Serpent', 'Galleon');
insert into ship (Sid, Name, Type) values (19, 'Gallows Light', 'Sloop');
insert into ship (Sid, Name, Type) values (20, 'The Ebon Drake', 'Sloop');
insert into ship (Sid, Name, Type) values (21, 'Ghostwake', 'Sloop');
insert into ship (Sid, Name, Type) values (22, 'Bloodwake Marauder', 'Brigantine');
insert into ship (Sid, Name, Type) values (23, 'Grimward', 'Sloop');
insert into ship (Sid, Name, Type) values (24, 'Silverfin', 'Brigantine');
insert into ship (Sid, Name, Type) values (25, 'Deepstar Marauder', 'Sloop');
insert into ship (Sid, Name, Type) values (26, 'Frostbite Raider', 'Galleon');
insert into ship (Sid, Name, Type) values (27, 'Bloodmoon Brig', 'Frigate');
insert into ship (Sid, Name, Type) values (28, 'Leviathan’s Roar', 'Sloop');
insert into ship (Sid, Name, Type) values (29, 'Broken Wing', 'Frigate');
insert into ship (Sid, Name, Type) values (30, 'Rotborn Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (31, 'Darkmoon Marauder', 'Brigantine');
insert into ship (Sid, Name, Type) values (32, 'Thunder Serpent', 'Brigantine');
insert into ship (Sid, Name, Type) values (33, 'Coral Reaper', 'Barque');
insert into ship (Sid, Name, Type) values (34, 'Bone Ripper', 'Barque');
insert into ship (Sid, Name, Type) values (35, 'Bloodwhale', 'Frigate');
insert into ship (Sid, Name, Type) values (36, 'Blight of the Deep', 'Barque');
insert into ship (Sid, Name, Type) values (37, 'Cursed Riptide', 'Brigantine');
insert into ship (Sid, Name, Type) values (38, 'Deadcurrent', 'Barque');
insert into ship (Sid, Name, Type) values (39, 'Rottentide Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (40, 'The Drowned Maiden', 'Sloop');
insert into ship (Sid, Name, Type) values (41, 'Devil’s Crest', 'Galleon');
insert into ship (Sid, Name, Type) values (42, 'Red Skull Warden', 'Galleon');
insert into ship (Sid, Name, Type) values (43, 'Hollowwake Warden.', 'Frigate');
insert into ship (Sid, Name, Type) values (44, 'Starlit Marauder', 'Sloop');
insert into ship (Sid, Name, Type) values (45, 'Wretched Serpent', 'Barque');
insert into ship (Sid, Name, Type) values (46, 'Scourgewind', 'Barque');
insert into ship (Sid, Name, Type) values (47, 'The Ashen Revenant', 'Brigantine');
insert into ship (Sid, Name, Type) values (48, 'Bloodgale', 'Frigate');
insert into ship (Sid, Name, Type) values (49, 'The Ragged Talon', 'Galleon');
insert into ship (Sid, Name, Type) values (50, 'Deadwave Brig', 'Brigantine');
insert into ship (Sid, Name, Type) values (51, 'Blight of the Deep', 'Barque');
insert into ship (Sid, Name, Type) values (52, 'Red Warden', 'Brigantine');
insert into ship (Sid, Name, Type) values (53, 'Sea Serpent’s Coil', 'Sloop');
insert into ship (Sid, Name, Type) values (54, 'The Crimson Reaper', 'Brigantine');
insert into ship (Sid, Name, Type) values (55, 'Wreck of the Damned', 'Galleon');
insert into ship (Sid, Name, Type) values (56, 'The Ashen Star', 'Barque');
insert into ship (Sid, Name, Type) values (57, 'Bloodharbor', 'Barque');
insert into ship (Sid, Name, Type) values (58, 'Ebonclaw', 'Frigate');
insert into ship (Sid, Name, Type) values (59, 'Tempest Queen', 'Brigantine');
insert into ship (Sid, Name, Type) values (60, 'Starlit Marauder', 'Galleon');
insert into ship (Sid, Name, Type) values (61, 'The Ashen Mistress', 'Frigate');
insert into ship (Sid, Name, Type) values (62, 'The Drowned Maiden', 'Barque');
insert into ship (Sid, Name, Type) values (63, 'Blackblood Mariner', 'Galleon');
insert into ship (Sid, Name, Type) values (64, 'Thundercaller', 'Brigantine');
insert into ship (Sid, Name, Type) values (65, 'The Silent Dagger', 'Frigate');
insert into ship (Sid, Name, Type) values (66, 'Sea Serpent’s Coil', 'Barque');
insert into ship (Sid, Name, Type) values (67, 'Salted Doom', 'Galleon');
insert into ship (Sid, Name, Type) values (68, 'Sea Phantom', 'Sloop');
insert into ship (Sid, Name, Type) values (69, 'Marrow''s End', 'Sloop');
insert into ship (Sid, Name, Type) values (70, 'Starless Phantom', 'Brigantine');
insert into ship (Sid, Name, Type) values (71, 'The Sinking Specter', 'Sloop');
insert into ship (Sid, Name, Type) values (72, 'Saltblood', 'Galleon');
insert into ship (Sid, Name, Type) values (73, 'Bloodmoon Brig', 'Barque');
insert into ship (Sid, Name, Type) values (74, 'Bloodwake Marauder', 'Frigate');
insert into ship (Sid, Name, Type) values (75, 'Leviathan’s Roar', 'Barque');
insert into ship (Sid, Name, Type) values (76, 'Black Reef Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (77, 'Rustscale Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (78, 'The Forgotten Raider', 'Galleon');
insert into ship (Sid, Name, Type) values (79, 'Lantern’s Curse', 'Sloop');
insert into ship (Sid, Name, Type) values (80, 'Kraken''s Doom', 'Frigate');
insert into ship (Sid, Name, Type) values (81, 'Saltdrinker', 'Barque');
insert into ship (Sid, Name, Type) values (82, 'Grimward', 'Brigantine');
insert into ship (Sid, Name, Type) values (83, 'Wailing Horizon', 'Sloop');
insert into ship (Sid, Name, Type) values (84, 'Stormchaser', 'Brigantine');
insert into ship (Sid, Name, Type) values (85, 'Shattered Fortune', 'Galleon');
insert into ship (Sid, Name, Type) values (86, 'Bone Ripper', 'Sloop');
insert into ship (Sid, Name, Type) values (87, 'The Duskwind', 'Frigate');
insert into ship (Sid, Name, Type) values (88, 'The Duskwind', 'Frigate');
insert into ship (Sid, Name, Type) values (89, 'Broken Marlin', 'Frigate');
insert into ship (Sid, Name, Type) values (90, 'Saltscourge', 'Galleon');
insert into ship (Sid, Name, Type) values (91, 'Grimdrift', 'Frigate');
insert into ship (Sid, Name, Type) values (92, 'Wretched Serpent', 'Frigate');
insert into ship (Sid, Name, Type) values (93, 'Rotten Jewel', 'Brigantine');
insert into ship (Sid, Name, Type) values (94, 'Frost Siren', 'Sloop');
insert into ship (Sid, Name, Type) values (95, 'Sunken Eclipse', 'Frigate');
insert into ship (Sid, Name, Type) values (96, 'Shadeclaw Raider', 'Frigate');
insert into ship (Sid, Name, Type) values (97, 'The Rusted Saber', 'Sloop');
insert into ship (Sid, Name, Type) values (98, 'Thundercaller', 'Sloop');
insert into ship (Sid, Name, Type) values (99, 'Bloodwake Marauder', 'Brigantine');
insert into ship (Sid, Name, Type) values (100, 'The Ashen Mistress', 'Barque');
insert into ship (Sid, Name, Type) values (101, 'Twisted Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (102, 'Iron Marlin', 'Frigate');
insert into ship (Sid, Name, Type) values (103, 'Darkmoon Marauder', 'Sloop');
insert into ship (Sid, Name, Type) values (104, 'Broken Marlin', 'Galleon');
insert into ship (Sid, Name, Type) values (105, 'Sunken Sabers', 'Barque');
insert into ship (Sid, Name, Type) values (106, 'Rotten Jewel', 'Sloop');
insert into ship (Sid, Name, Type) values (107, 'Midnight Crown', 'Brigantine');
insert into ship (Sid, Name, Type) values (108, 'Saltscourge', 'Frigate');
insert into ship (Sid, Name, Type) values (109, 'Marrow''s End', 'Sloop');
insert into ship (Sid, Name, Type) values (110, 'Dead Man’s Fancy', 'Sloop');
insert into ship (Sid, Name, Type) values (111, 'Silverfin', 'Brigantine');
insert into ship (Sid, Name, Type) values (112, 'Ghosttide', 'Brigantine');
insert into ship (Sid, Name, Type) values (113, 'Black Reef Raider', 'Frigate');
insert into ship (Sid, Name, Type) values (114, 'Broken Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (115, 'Death''s Embrace', 'Sloop');
insert into ship (Sid, Name, Type) values (116, 'Twilight Corsair', 'Galleon');
insert into ship (Sid, Name, Type) values (117, 'The Bleeding Tide', 'Barque');
insert into ship (Sid, Name, Type) values (118, 'Twilight Corsair', 'Brigantine');
insert into ship (Sid, Name, Type) values (119, 'The Gallows Ghost', 'Sloop');
insert into ship (Sid, Name, Type) values (120, 'Broken Compass', 'Frigate');
insert into ship (Sid, Name, Type) values (121, 'The Forgotten Raider', 'Barque');
insert into ship (Sid, Name, Type) values (122, 'Wraithfin', 'Barque');
insert into ship (Sid, Name, Type) values (123, 'The Silent Dagger', 'Barque');
insert into ship (Sid, Name, Type) values (124, 'Black Sail’s Oath', 'Brigantine');
insert into ship (Sid, Name, Type) values (125, 'Bloodmoon Brig', 'Frigate');
insert into ship (Sid, Name, Type) values (126, 'Silent Torrent', 'Barque');
insert into ship (Sid, Name, Type) values (127, 'The Coral Phantom', 'Frigate');
insert into ship (Sid, Name, Type) values (128, 'Grim Haven', 'Brigantine');
insert into ship (Sid, Name, Type) values (129, 'Red Leviathan', 'Brigantine');
insert into ship (Sid, Name, Type) values (130, 'Crimsontide Raider', 'Frigate');
insert into ship (Sid, Name, Type) values (131, 'Stormbreaker', 'Sloop');
insert into ship (Sid, Name, Type) values (132, 'Red Leviathan', 'Brigantine');
insert into ship (Sid, Name, Type) values (133, 'Frostshadow', 'Brigantine');
insert into ship (Sid, Name, Type) values (134, 'Bloodwake Marauder', 'Frigate');
insert into ship (Sid, Name, Type) values (135, 'Voodoo Pearl', 'Galleon');
insert into ship (Sid, Name, Type) values (136, 'The Drowned Maiden', 'Barque');
insert into ship (Sid, Name, Type) values (137, 'Hollow Star', 'Galleon');
insert into ship (Sid, Name, Type) values (138, 'Pale Shark', 'Sloop');
insert into ship (Sid, Name, Type) values (139, 'Mistshroud', 'Galleon');
insert into ship (Sid, Name, Type) values (140, 'Tempest’s Fang', 'Galleon');
insert into ship (Sid, Name, Type) values (141, 'Sable Wraith', 'Brigantine');
insert into ship (Sid, Name, Type) values (142, 'The Crimson Reaper', 'Galleon');
insert into ship (Sid, Name, Type) values (143, 'Iron Marlin', 'Sloop');
insert into ship (Sid, Name, Type) values (144, 'Shattered Fortune', 'Barque');
insert into ship (Sid, Name, Type) values (145, 'The Scarlet Tempest', 'Sloop');
insert into ship (Sid, Name, Type) values (146, 'Deadstar Corsair', 'Sloop');
insert into ship (Sid, Name, Type) values (147, 'The Ragged Talon', 'Brigantine');
insert into ship (Sid, Name, Type) values (148, 'Cursed Skull', 'Frigate');
insert into ship (Sid, Name, Type) values (149, 'Red Warden', 'Barque');
insert into ship (Sid, Name, Type) values (150, 'Blight of the Deep', 'Galleon');
insert into ship (Sid, Name, Type) values (151, 'Gravewake', 'Barque');
insert into ship (Sid, Name, Type) values (152, 'Stormborn Revenant', 'Frigate');
insert into ship (Sid, Name, Type) values (153, 'Red Skull Warden', 'Frigate');
insert into ship (Sid, Name, Type) values (154, 'Abyssal Fang', 'Barque');
insert into ship (Sid, Name, Type) values (155, 'Plaguewind', 'Barque');
insert into ship (Sid, Name, Type) values (156, 'Hollow Warden', 'Sloop');
insert into ship (Sid, Name, Type) values (157, 'Broken Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (158, 'Black Siren', 'Galleon');
insert into ship (Sid, Name, Type) values (159, 'Midnight Crown', 'Brigantine');
insert into ship (Sid, Name, Type) values (160, 'The Bleeding Horizon', 'Barque');
insert into ship (Sid, Name, Type) values (161, 'The Drifting Doom', 'Galleon');
insert into ship (Sid, Name, Type) values (162, 'Devil’s Lantern', 'Frigate');
insert into ship (Sid, Name, Type) values (163, 'The Drifting Doom', 'Brigantine');
insert into ship (Sid, Name, Type) values (164, 'Sea Wolf', 'Galleon');
insert into ship (Sid, Name, Type) values (165, 'Night''s Embrace', 'Sloop');
insert into ship (Sid, Name, Type) values (166, 'Maelstrom’s Curse', 'Frigate');
insert into ship (Sid, Name, Type) values (167, 'Blightfin', 'Barque');
insert into ship (Sid, Name, Type) values (168, 'The Ashen Revenant', 'Galleon');
insert into ship (Sid, Name, Type) values (169, 'Cracked Skull', 'Galleon');
insert into ship (Sid, Name, Type) values (170, 'Crimsontide Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (171, 'Midnight Crown', 'Galleon');
insert into ship (Sid, Name, Type) values (172, 'Sea Serpent’s Coil', 'Sloop');
insert into ship (Sid, Name, Type) values (173, 'The Shattered Wave', 'Barque');
insert into ship (Sid, Name, Type) values (174, 'Ghost Fang', 'Frigate');
insert into ship (Sid, Name, Type) values (175, 'The Coral Widow', 'Frigate');
insert into ship (Sid, Name, Type) values (176, 'Cursed Riptide', 'Galleon');
insert into ship (Sid, Name, Type) values (177, 'Hollow Warden', 'Brigantine');
insert into ship (Sid, Name, Type) values (178, 'Red Leviathan', 'Barque');
insert into ship (Sid, Name, Type) values (179, 'Gallows Light', 'Barque');
insert into ship (Sid, Name, Type) values (180, 'Bone Ripper', 'Sloop');
insert into ship (Sid, Name, Type) values (181, 'Shattered Fortune', 'Sloop');
insert into ship (Sid, Name, Type) values (182, 'Thunder Serpent', 'Barque');
insert into ship (Sid, Name, Type) values (183, 'The Siren’s Blight', 'Brigantine');
insert into ship (Sid, Name, Type) values (184, 'Deepstar Marauder', 'Frigate');
insert into ship (Sid, Name, Type) values (185, 'Driftwood Phantom', 'Frigate');
insert into ship (Sid, Name, Type) values (186, 'Shadebreaker', 'Galleon');
insert into ship (Sid, Name, Type) values (187, 'Blight of the Deep', 'Frigate');
insert into ship (Sid, Name, Type) values (188, 'Bone Ripper', 'Brigantine');
insert into ship (Sid, Name, Type) values (189, 'Leviathan’s Howl', 'Sloop');
insert into ship (Sid, Name, Type) values (190, 'Hollow Warden', 'Barque');
insert into ship (Sid, Name, Type) values (191, 'Sea Phantom', 'Sloop');
insert into ship (Sid, Name, Type) values (192, 'Scourgewind', 'Barque');
insert into ship (Sid, Name, Type) values (193, 'Phantom’s Wake', 'Sloop');
insert into ship (Sid, Name, Type) values (194, 'Gallows Light', 'Barque');
insert into ship (Sid, Name, Type) values (195, 'Tempest Queen', 'Galleon');
insert into ship (Sid, Name, Type) values (196, 'Seafoam Marauder', 'Galleon');
insert into ship (Sid, Name, Type) values (197, 'Darkwater Serpent', 'Sloop');
insert into ship (Sid, Name, Type) values (198, 'Shadebreaker', 'Frigate');
insert into ship (Sid, Name, Type) values (199, 'Deepstar Marauder', 'Galleon');
insert into ship (Sid, Name, Type) values (200, 'Gallows Light', 'Barque');
insert into ship (Sid, Name, Type) values (201, 'The Shattered Wave', 'Sloop');
insert into ship (Sid, Name, Type) values (202, 'Starlit Marauder', 'Galleon');
insert into ship (Sid, Name, Type) values (203, 'Seafoam Marauder', 'Frigate');
insert into ship (Sid, Name, Type) values (204, 'Forsaken Spirit', 'Brigantine');
insert into ship (Sid, Name, Type) values (205, 'Riftbreaker', 'Brigantine');
insert into ship (Sid, Name, Type) values (206, 'Black Reef Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (207, 'Seabane Corsair', 'Frigate');
insert into ship (Sid, Name, Type) values (208, 'Wretched Corsair', 'Frigate');
insert into ship (Sid, Name, Type) values (209, 'Rotten Jewel', 'Brigantine');
insert into ship (Sid, Name, Type) values (210, 'Thundertide', 'Sloop');
insert into ship (Sid, Name, Type) values (211, 'Drowned Dreamer', 'Sloop');
insert into ship (Sid, Name, Type) values (212, 'Ironhowl', 'Barque');
insert into ship (Sid, Name, Type) values (213, 'Thundercaller', 'Sloop');
insert into ship (Sid, Name, Type) values (214, 'Bloodsail Raider', 'Barque');
insert into ship (Sid, Name, Type) values (215, 'The Siren’s Blight', 'Frigate');
insert into ship (Sid, Name, Type) values (216, 'Seafoam Marauder', 'Barque');
insert into ship (Sid, Name, Type) values (217, 'Stormchaser', 'Sloop');
insert into ship (Sid, Name, Type) values (218, 'Wreck of the Damned', 'Brigantine');
insert into ship (Sid, Name, Type) values (219, 'Tempest Serpent', 'Brigantine');
insert into ship (Sid, Name, Type) values (220, 'Salted Doom', 'Brigantine');
insert into ship (Sid, Name, Type) values (221, 'Hollowwake Warden.', 'Galleon');
insert into ship (Sid, Name, Type) values (222, 'Red Widow', 'Barque');
insert into ship (Sid, Name, Type) values (223, 'Stormborn Revenant', 'Galleon');
insert into ship (Sid, Name, Type) values (224, 'Darktide', 'Brigantine');
insert into ship (Sid, Name, Type) values (225, 'Leviathan’s Roar', 'Galleon');
insert into ship (Sid, Name, Type) values (226, 'Riftbreaker', 'Brigantine');
insert into ship (Sid, Name, Type) values (227, 'Death Shark', 'Brigantine');
insert into ship (Sid, Name, Type) values (228, 'Grimdrift', 'Frigate');
insert into ship (Sid, Name, Type) values (229, 'The Sable Tempest', 'Frigate');
insert into ship (Sid, Name, Type) values (230, 'Deadwave Brig', 'Frigate');
insert into ship (Sid, Name, Type) values (231, 'The Siren’s Blight', 'Sloop');
insert into ship (Sid, Name, Type) values (232, 'Ebonclaw', 'Frigate');
insert into ship (Sid, Name, Type) values (233, 'The Ragged Talon', 'Barque');
insert into ship (Sid, Name, Type) values (234, 'Stormbreaker', 'Galleon');
insert into ship (Sid, Name, Type) values (235, 'Crimsontide Raider', 'Frigate');
insert into ship (Sid, Name, Type) values (236, 'Kraken’s Wrath', 'Frigate');
insert into ship (Sid, Name, Type) values (237, 'The Grim Albatross', 'Sloop');
insert into ship (Sid, Name, Type) values (238, 'The Drowned Maiden', 'Brigantine');
insert into ship (Sid, Name, Type) values (239, 'The Shrieking Siren', 'Sloop');
insert into ship (Sid, Name, Type) values (240, 'The Sable Tempest', 'Frigate');
insert into ship (Sid, Name, Type) values (241, 'Phantom’s Wake', 'Brigantine');
insert into ship (Sid, Name, Type) values (242, 'Saltdrinker', 'Galleon');
insert into ship (Sid, Name, Type) values (243, 'Red Skull Warden', 'Galleon');
insert into ship (Sid, Name, Type) values (244, 'Red Skull Warden', 'Barque');
insert into ship (Sid, Name, Type) values (245, 'The Sinking Specter', 'Brigantine');
insert into ship (Sid, Name, Type) values (246, 'Death Shark', 'Brigantine');
insert into ship (Sid, Name, Type) values (247, 'Rotborn Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (248, 'Red Leviathan', 'Sloop');
insert into ship (Sid, Name, Type) values (249, 'Bloodgale', 'Sloop');
insert into ship (Sid, Name, Type) values (250, 'The Ashen Mistress', 'Frigate');
insert into ship (Sid, Name, Type) values (251, 'Bloodwake Marauder', 'Galleon');
insert into ship (Sid, Name, Type) values (252, 'Pale Blade', 'Sloop');
insert into ship (Sid, Name, Type) values (253, 'Deathcurrent', 'Brigantine');
insert into ship (Sid, Name, Type) values (254, 'Black Sail’s Oath', 'Frigate');
insert into ship (Sid, Name, Type) values (255, 'The Scarlet Tempest', 'Frigate');
insert into ship (Sid, Name, Type) values (256, 'The Ashen Star', 'Frigate');
insert into ship (Sid, Name, Type) values (257, 'Darkwater Serpent', 'Frigate');
insert into ship (Sid, Name, Type) values (258, 'Drowned Dreamer', 'Galleon');
insert into ship (Sid, Name, Type) values (259, 'Saltblood', 'Brigantine');
insert into ship (Sid, Name, Type) values (260, 'Cursed Marlin', 'Sloop');
insert into ship (Sid, Name, Type) values (261, 'Rustfang', 'Barque');
insert into ship (Sid, Name, Type) values (262, 'Hollow Star', 'Galleon');
insert into ship (Sid, Name, Type) values (263, 'Pale Leviathan', 'Barque');
insert into ship (Sid, Name, Type) values (264, 'Rotten Jewel', 'Galleon');
insert into ship (Sid, Name, Type) values (265, 'Hollowwake Warden.', 'Galleon');
insert into ship (Sid, Name, Type) values (266, 'Blackwater Wraith', 'Galleon');
insert into ship (Sid, Name, Type) values (267, 'Starless Phantom', 'Brigantine');
insert into ship (Sid, Name, Type) values (268, 'Gallows Light', 'Brigantine');
insert into ship (Sid, Name, Type) values (269, 'Siren’s Vengeance', 'Sloop');
insert into ship (Sid, Name, Type) values (270, 'Death''s Embrace', 'Galleon');
insert into ship (Sid, Name, Type) values (271, 'Iron Marlin', 'Galleon');
insert into ship (Sid, Name, Type) values (272, 'Crimsontide Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (273, 'Devil’s Mistress', 'Sloop');
insert into ship (Sid, Name, Type) values (274, 'Gallows Anchor', 'Sloop');
insert into ship (Sid, Name, Type) values (275, 'Broken Lantern', 'Sloop');
insert into ship (Sid, Name, Type) values (276, 'Burning Marlin', 'Barque');
insert into ship (Sid, Name, Type) values (277, 'Sunken Fury', 'Galleon');
insert into ship (Sid, Name, Type) values (278, 'Maelstrom’s Curse', 'Sloop');
insert into ship (Sid, Name, Type) values (279, 'Silent Revenant', 'Galleon');
insert into ship (Sid, Name, Type) values (280, 'Thundercaller', 'Galleon');
insert into ship (Sid, Name, Type) values (281, 'Darktide', 'Sloop');
insert into ship (Sid, Name, Type) values (282, 'Red Warden', 'Barque');
insert into ship (Sid, Name, Type) values (283, 'Burning Marlin', 'Sloop');
insert into ship (Sid, Name, Type) values (284, 'Salted Doom', 'Barque');
insert into ship (Sid, Name, Type) values (285, 'Stormchaser', 'Barque');
insert into ship (Sid, Name, Type) values (286, 'Iron Marlin', 'Galleon');
insert into ship (Sid, Name, Type) values (287, 'Iron Keel', 'Sloop');
insert into ship (Sid, Name, Type) values (288, 'Broken Wing', 'Barque');
insert into ship (Sid, Name, Type) values (289, 'Shadeclaw Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (290, 'Gallows Light', 'Sloop');
insert into ship (Sid, Name, Type) values (291, 'Seabane Corsair', 'Frigate');
insert into ship (Sid, Name, Type) values (292, 'The Crimson Reaper', 'Frigate');
insert into ship (Sid, Name, Type) values (293, 'Phantom’s Wake', 'Barque');
insert into ship (Sid, Name, Type) values (294, 'The Siren’s Blight', 'Sloop');
insert into ship (Sid, Name, Type) values (295, 'Black Reef Raider', 'Frigate');
insert into ship (Sid, Name, Type) values (296, 'Frost Siren', 'Barque');
insert into ship (Sid, Name, Type) values (297, 'Brinewolf', 'Barque');
insert into ship (Sid, Name, Type) values (298, 'Cursed Drake', 'Brigantine');
insert into ship (Sid, Name, Type) values (299, 'Ebonclaw', 'Frigate');
insert into ship (Sid, Name, Type) values (300, 'Silent Torrent', 'Brigantine');
insert into ship (Sid, Name, Type) values (301, 'Specter’s Wake', 'Sloop');
insert into ship (Sid, Name, Type) values (302, 'Burning Marlin', 'Sloop');
insert into ship (Sid, Name, Type) values (303, 'Red Leviathan', 'Frigate');
insert into ship (Sid, Name, Type) values (304, 'Pale Lantern', 'Sloop');
insert into ship (Sid, Name, Type) values (305, 'The Gallows Ghost', 'Sloop');
insert into ship (Sid, Name, Type) values (306, 'The Sunken Star', 'Galleon');
insert into ship (Sid, Name, Type) values (307, 'Serpent’s Bane', 'Galleon');
insert into ship (Sid, Name, Type) values (308, 'Red Skull Warden', 'Frigate');
insert into ship (Sid, Name, Type) values (309, 'Sunken Eclipse', 'Frigate');
insert into ship (Sid, Name, Type) values (310, 'Boneharbor Brig', 'Galleon');
insert into ship (Sid, Name, Type) values (311, 'Daggerfin', 'Sloop');
insert into ship (Sid, Name, Type) values (312, 'The Hollow Marlin', 'Galleon');
insert into ship (Sid, Name, Type) values (313, 'Bloodsail Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (314, 'The Blighted Jewel', 'Barque');
insert into ship (Sid, Name, Type) values (315, 'Salted Doom', 'Galleon');
insert into ship (Sid, Name, Type) values (316, 'Hollowwake Warden.', 'Brigantine');
insert into ship (Sid, Name, Type) values (317, 'Gallows Light', 'Galleon');
insert into ship (Sid, Name, Type) values (318, 'Leviathan’s Roar', 'Brigantine');
insert into ship (Sid, Name, Type) values (319, 'Devil’s Lantern', 'Sloop');
insert into ship (Sid, Name, Type) values (320, 'Red Warden', 'Sloop');
insert into ship (Sid, Name, Type) values (321, 'Black Reef Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (322, 'Hollowwake Warden.', 'Frigate');
insert into ship (Sid, Name, Type) values (323, 'The Sinking Specter', 'Sloop');
insert into ship (Sid, Name, Type) values (324, 'Pale Blade', 'Frigate');
insert into ship (Sid, Name, Type) values (325, 'Sunken Fury', 'Frigate');
insert into ship (Sid, Name, Type) values (326, 'Rotten Jewel', 'Brigantine');
insert into ship (Sid, Name, Type) values (327, 'Shadebreaker', 'Sloop');
insert into ship (Sid, Name, Type) values (328, 'Gallows Anchor', 'Galleon');
insert into ship (Sid, Name, Type) values (329, 'Sunken Sabers', 'Brigantine');
insert into ship (Sid, Name, Type) values (330, 'The Bleeding Horizon', 'Brigantine');
insert into ship (Sid, Name, Type) values (331, 'Midnight Crown', 'Barque');
insert into ship (Sid, Name, Type) values (332, 'Darkmoon Marauder', 'Sloop');
insert into ship (Sid, Name, Type) values (333, 'Cracked Skull', 'Frigate');
insert into ship (Sid, Name, Type) values (334, 'Bloodharbor', 'Sloop');
insert into ship (Sid, Name, Type) values (335, 'Bone Ripper', 'Frigate');
insert into ship (Sid, Name, Type) values (336, 'Daggerfin', 'Brigantine');
insert into ship (Sid, Name, Type) values (337, 'Seabane Corsair', 'Frigate');
insert into ship (Sid, Name, Type) values (338, 'Maelstrom’s Curse', 'Frigate');
insert into ship (Sid, Name, Type) values (339, 'The Duskwind', 'Brigantine');
insert into ship (Sid, Name, Type) values (340, 'Cracked Skull', 'Frigate');
insert into ship (Sid, Name, Type) values (341, 'Abyssal Fang', 'Frigate');
insert into ship (Sid, Name, Type) values (342, 'Ironhowl', 'Frigate');
insert into ship (Sid, Name, Type) values (343, 'The Silent Dagger', 'Frigate');
insert into ship (Sid, Name, Type) values (344, 'Devil’s Crest', 'Frigate');
insert into ship (Sid, Name, Type) values (345, 'Silent Revenant', 'Sloop');
insert into ship (Sid, Name, Type) values (346, 'Coral Reaper', 'Frigate');
insert into ship (Sid, Name, Type) values (347, 'Crimsontide Raider', 'Barque');
insert into ship (Sid, Name, Type) values (348, 'The Maelstrom’s Kiss', 'Sloop');
insert into ship (Sid, Name, Type) values (349, 'Tempest’s Fang', 'Brigantine');
insert into ship (Sid, Name, Type) values (350, 'Sunken Eclipse', 'Galleon');
insert into ship (Sid, Name, Type) values (351, 'Sable Corsair', 'Brigantine');
insert into ship (Sid, Name, Type) values (352, 'Rottentide Raider', 'Barque');
insert into ship (Sid, Name, Type) values (353, 'Red Warden', 'Sloop');
insert into ship (Sid, Name, Type) values (354, 'Salted Doom', 'Frigate');
insert into ship (Sid, Name, Type) values (355, 'Saltblood', 'Galleon');
insert into ship (Sid, Name, Type) values (356, 'Bloodwhale', 'Barque');
insert into ship (Sid, Name, Type) values (357, 'Saltscourge', 'Sloop');
insert into ship (Sid, Name, Type) values (358, 'The Ashen Mistress', 'Sloop');
insert into ship (Sid, Name, Type) values (359, 'Gravecurrent', 'Brigantine');
insert into ship (Sid, Name, Type) values (360, 'The Siren’s Blight', 'Brigantine');
insert into ship (Sid, Name, Type) values (361, 'The Ebon Drake', 'Barque');
insert into ship (Sid, Name, Type) values (362, 'Brinewolf', 'Galleon');
insert into ship (Sid, Name, Type) values (363, 'Death''s Embrace', 'Barque');
insert into ship (Sid, Name, Type) values (364, 'Frostshadow', 'Frigate');
insert into ship (Sid, Name, Type) values (365, 'Riftbreaker', 'Brigantine');
insert into ship (Sid, Name, Type) values (366, 'Driftwood Phantom', 'Galleon');
insert into ship (Sid, Name, Type) values (367, 'Sea Serpent’s Coil', 'Galleon');
insert into ship (Sid, Name, Type) values (368, 'Bloodgale', 'Frigate');
insert into ship (Sid, Name, Type) values (369, 'Marrow''s End', 'Brigantine');
insert into ship (Sid, Name, Type) values (370, 'Rustfang', 'Brigantine');
insert into ship (Sid, Name, Type) values (371, 'Devil’s Crest', 'Brigantine');
insert into ship (Sid, Name, Type) values (372, 'Saltscourge', 'Sloop');
insert into ship (Sid, Name, Type) values (373, 'Ghostwake', 'Frigate');
insert into ship (Sid, Name, Type) values (374, 'Twisted Compass', 'Barque');
insert into ship (Sid, Name, Type) values (375, 'Devil’s Mistress', 'Brigantine');
insert into ship (Sid, Name, Type) values (376, 'Salted Doom', 'Sloop');
insert into ship (Sid, Name, Type) values (377, 'Twisted Compass', 'Galleon');
insert into ship (Sid, Name, Type) values (378, 'Ebon Mariner', 'Galleon');
insert into ship (Sid, Name, Type) values (379, 'Nightshade’s Fury', 'Galleon');
insert into ship (Sid, Name, Type) values (380, 'Midnight Crown', 'Barque');
insert into ship (Sid, Name, Type) values (381, 'Marrow''s End', 'Frigate');
insert into ship (Sid, Name, Type) values (382, 'Pale Leviathan', 'Brigantine');
insert into ship (Sid, Name, Type) values (383, 'Leviathan’s Roar', 'Brigantine');
insert into ship (Sid, Name, Type) values (384, 'Sea Wolf', 'Sloop');
insert into ship (Sid, Name, Type) values (385, 'Ebonclaw', 'Galleon');
insert into ship (Sid, Name, Type) values (386, 'The Rotten Crown', 'Frigate');
insert into ship (Sid, Name, Type) values (387, 'Ironfang Warden', 'Frigate');
insert into ship (Sid, Name, Type) values (388, 'Broken Lantern', 'Sloop');
insert into ship (Sid, Name, Type) values (389, 'The Bleeding Tide', 'Galleon');
insert into ship (Sid, Name, Type) values (390, 'Ironfang Warden', 'Brigantine');
insert into ship (Sid, Name, Type) values (391, 'Blight of the Deep', 'Sloop');
insert into ship (Sid, Name, Type) values (392, 'The Siren’s Blight', 'Galleon');
insert into ship (Sid, Name, Type) values (393, 'Wailing Widow', 'Brigantine');
insert into ship (Sid, Name, Type) values (394, 'Burning Marlin', 'Sloop');
insert into ship (Sid, Name, Type) values (395, 'Pale Shark', 'Frigate');
insert into ship (Sid, Name, Type) values (396, 'Widow’s Fang', 'Brigantine');
insert into ship (Sid, Name, Type) values (397, 'The Rusted Saber', 'Frigate');
insert into ship (Sid, Name, Type) values (398, 'Rotfin Corsair', 'Brigantine');
insert into ship (Sid, Name, Type) values (399, 'Maelstrom’s Curse', 'Frigate');
insert into ship (Sid, Name, Type) values (400, 'Rotborn Raider', 'Frigate');
insert into ship (Sid, Name, Type) values (401, 'The Drifting Doom', 'Brigantine');
insert into ship (Sid, Name, Type) values (402, 'Saltblood', 'Frigate');
insert into ship (Sid, Name, Type) values (403, 'The Scarlet Tempest', 'Frigate');
insert into ship (Sid, Name, Type) values (404, 'Bloodwake Marauder', 'Sloop');
insert into ship (Sid, Name, Type) values (405, 'Moonfang Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (406, 'Thundercaller', 'Brigantine');
insert into ship (Sid, Name, Type) values (407, 'The Grim Albatross', 'Sloop');
insert into ship (Sid, Name, Type) values (408, 'Gallows Light', 'Brigantine');
insert into ship (Sid, Name, Type) values (409, 'Deathcurrent', 'Brigantine');
insert into ship (Sid, Name, Type) values (410, 'Abysswatcher', 'Brigantine');
insert into ship (Sid, Name, Type) values (411, 'Cursed Skull', 'Sloop');
insert into ship (Sid, Name, Type) values (412, 'Cracked Skull', 'Brigantine');
insert into ship (Sid, Name, Type) values (413, 'Bleeding Compass', 'Barque');
insert into ship (Sid, Name, Type) values (414, 'Ironhowl', 'Frigate');
insert into ship (Sid, Name, Type) values (415, 'Twisted Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (416, 'Ghosttide', 'Sloop');
insert into ship (Sid, Name, Type) values (417, 'Boneharbor Brig', 'Frigate');
insert into ship (Sid, Name, Type) values (418, 'Starless Phantom', 'Frigate');
insert into ship (Sid, Name, Type) values (419, 'Moonfang Raider', 'Barque');
insert into ship (Sid, Name, Type) values (420, 'Riftbreaker', 'Frigate');
insert into ship (Sid, Name, Type) values (421, 'Bleeding Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (422, 'Deadwave Brig', 'Frigate');
insert into ship (Sid, Name, Type) values (423, 'Silentbone', 'Galleon');
insert into ship (Sid, Name, Type) values (424, 'Cursed Skull', 'Frigate');
insert into ship (Sid, Name, Type) values (425, 'Frost Siren', 'Barque');
insert into ship (Sid, Name, Type) values (426, 'Silentbone', 'Galleon');
insert into ship (Sid, Name, Type) values (427, 'Wailing Widow', 'Sloop');
insert into ship (Sid, Name, Type) values (428, 'The Crimson Reaper', 'Frigate');
insert into ship (Sid, Name, Type) values (429, 'Broken Marlin', 'Frigate');
insert into ship (Sid, Name, Type) values (430, 'Leviathan’s Howl', 'Sloop');
insert into ship (Sid, Name, Type) values (431, 'Gallows Anchor', 'Frigate');
insert into ship (Sid, Name, Type) values (432, 'Silent Revenant', 'Galleon');
insert into ship (Sid, Name, Type) values (433, 'Brinewolf', 'Brigantine');
insert into ship (Sid, Name, Type) values (434, 'Rotfin Corsair', 'Sloop');
insert into ship (Sid, Name, Type) values (435, 'Devil’s Lantern', 'Frigate');
insert into ship (Sid, Name, Type) values (436, 'The Blighted Jewel', 'Frigate');
insert into ship (Sid, Name, Type) values (437, 'Gravewake', 'Sloop');
insert into ship (Sid, Name, Type) values (438, 'Ghosttide', 'Brigantine');
insert into ship (Sid, Name, Type) values (439, 'The Blighted Jewel', 'Galleon');
insert into ship (Sid, Name, Type) values (440, 'Cursed Drake', 'Barque');
insert into ship (Sid, Name, Type) values (441, 'Nightshade’s Fury', 'Galleon');
insert into ship (Sid, Name, Type) values (442, 'Deadlight', 'Galleon');
insert into ship (Sid, Name, Type) values (443, 'Iron Marlin', 'Barque');
insert into ship (Sid, Name, Type) values (444, 'Stormbreaker', 'Sloop');
insert into ship (Sid, Name, Type) values (445, 'Drowned Dreamer', 'Brigantine');
insert into ship (Sid, Name, Type) values (446, 'Drowned Wraith', 'Frigate');
insert into ship (Sid, Name, Type) values (447, 'Bloodsail Raider', 'Brigantine');
insert into ship (Sid, Name, Type) values (448, 'Tidemourn', 'Sloop');
insert into ship (Sid, Name, Type) values (449, 'Boneharbor Brig', 'Barque');
insert into ship (Sid, Name, Type) values (450, 'Cracked Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (451, 'Dead Man’s Fancy', 'Galleon');
insert into ship (Sid, Name, Type) values (452, 'Rottentide Raider', 'Barque');
insert into ship (Sid, Name, Type) values (453, 'Devil’s Lantern', 'Brigantine');
insert into ship (Sid, Name, Type) values (454, 'Hollow Warden', 'Sloop');
insert into ship (Sid, Name, Type) values (455, 'Sable Corsair', 'Barque');
insert into ship (Sid, Name, Type) values (456, 'The Coral Phantom', 'Brigantine');
insert into ship (Sid, Name, Type) values (457, 'Black Siren', 'Brigantine');
insert into ship (Sid, Name, Type) values (458, 'Red Skull Warden', 'Sloop');
insert into ship (Sid, Name, Type) values (459, 'Sea Phantom', 'Frigate');
insert into ship (Sid, Name, Type) values (460, 'The Siren’s Blight', 'Barque');
insert into ship (Sid, Name, Type) values (461, 'Widow’s Fang', 'Galleon');
insert into ship (Sid, Name, Type) values (462, 'Shadeclaw Raider', 'Barque');
insert into ship (Sid, Name, Type) values (463, 'Blightfin', 'Brigantine');
insert into ship (Sid, Name, Type) values (464, 'The Ragged Talon', 'Sloop');
insert into ship (Sid, Name, Type) values (465, 'Ghost Fang', 'Brigantine');
insert into ship (Sid, Name, Type) values (466, 'Crimsontide Raider', 'Galleon');
insert into ship (Sid, Name, Type) values (467, 'Nightshade’s Fury', 'Barque');
insert into ship (Sid, Name, Type) values (468, 'Sable Corsair', 'Barque');
insert into ship (Sid, Name, Type) values (469, 'Abyssal Fang', 'Galleon');
insert into ship (Sid, Name, Type) values (470, 'Frost Siren', 'Frigate');
insert into ship (Sid, Name, Type) values (471, 'Cursed Riptide', 'Barque');
insert into ship (Sid, Name, Type) values (472, 'The Sable Tempest', 'Galleon');
insert into ship (Sid, Name, Type) values (473, 'Plaguewind', 'Sloop');
insert into ship (Sid, Name, Type) values (474, 'Bleeding Compass', 'Sloop');
insert into ship (Sid, Name, Type) values (475, 'Riftbreaker', 'Galleon');
insert into ship (Sid, Name, Type) values (476, 'Blackblood Mariner', 'Brigantine');
insert into ship (Sid, Name, Type) values (477, 'Blackwater Wraith', 'Sloop');
insert into ship (Sid, Name, Type) values (478, 'Sea Serpent’s Coil', 'Sloop');
insert into ship (Sid, Name, Type) values (479, 'Kraken’s Wrath', 'Sloop');
insert into ship (Sid, Name, Type) values (480, 'Stormchaser', 'Sloop');
insert into ship (Sid, Name, Type) values (481, 'Broken Wing', 'Frigate');
insert into ship (Sid, Name, Type) values (482, 'Broken Wing', 'Sloop');
insert into ship (Sid, Name, Type) values (483, 'Tempest Queen', 'Frigate');
insert into ship (Sid, Name, Type) values (484, 'Starlit Marauder', 'Galleon');
insert into ship (Sid, Name, Type) values (485, 'The Forgotten Raider', 'Sloop');
insert into ship (Sid, Name, Type) values (486, 'Grim Haven', 'Sloop');
insert into ship (Sid, Name, Type) values (487, 'Pale Lantern', 'Frigate');
insert into ship (Sid, Name, Type) values (488, 'The Duskwind', 'Sloop');
insert into ship (Sid, Name, Type) values (489, 'Iron Keel', 'Frigate');
insert into ship (Sid, Name, Type) values (490, 'Wailing Horizon', 'Frigate');
insert into ship (Sid, Name, Type) values (491, 'The Scarlet Sinker', 'Sloop');
insert into ship (Sid, Name, Type) values (492, 'Thundertide', 'Sloop');
insert into ship (Sid, Name, Type) values (493, 'Deadcurrent', 'Galleon');
insert into ship (Sid, Name, Type) values (494, 'Siren’s Teeth', 'Sloop');
insert into ship (Sid, Name, Type) values (495, 'Shattered Fortune', 'Sloop');
insert into ship (Sid, Name, Type) values (496, 'Midnight Crown', 'Sloop');
insert into ship (Sid, Name, Type) values (497, 'Pale Shark', 'Galleon');
insert into ship (Sid, Name, Type) values (498, 'Starlit Marauder', 'Brigantine');
insert into ship (Sid, Name, Type) values (499, 'Serpent’s Bane', 'Galleon');
insert into ship (Sid, Name, Type) values (500, 'Grimdrift', 'Barque');
