insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (1, 2, 'Bloodwake Raiders', 'Battle of the Titans', 39396.4, 'Blackreef Lagoon', '1743-10-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (2, 2, 'The Scarlet Wraiths', 'Clash of the Champions', 99239.9, 'Bloodwake Bay', '1707-09-28');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (3, 2, 'Bone Reef Marauders', 'War of the Worlds', 69881.95, 'Skeleton Cove', '1608-06-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (4, 2, 'The Rusted Cutlasses', 'Skirmish at Sunset', 6284.81, 'The Drowned Isles', '1796-10-25');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (5, 1, 'The Siren’s Howl', 'Siege of the Stronghold', 67693.89, 'Broken Mast Bay', '1797-07-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (6, 7, 'Ironfang Buccaneers', 'Rumble in the Jungle', 22866.64, 'Shadowmist Isle', '1700-10-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (7, 4, 'The Broken Compass', 'Showdown at High Noon', 53882.43, 'Daggerjaw Shoals', '1699-08-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (8, 3, 'Crimson Corsairs', 'Conquest of the Kingdom', 60266.73, 'Skeleton Cove', '1631-04-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (9, 3, 'Grimwater Gang', 'Brawl at the Barrens', 70649.38, 'Shattered Compass Key', '1721-05-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (10, 4, 'The Daggerfangs', 'Duel in the Desert', 12783.21, 'Shattered Compass Key', '1612-12-28');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (11, 2, 'The Black Tide', 'Battle of the Titans', 59371.32, 'Blackreef Lagoon', '1650-01-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (12, 5, 'Leviathan’s Bane', 'Clash of the Champions', 22168.15, 'Stormwreck Atoll', '1766-03-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (13, 3, 'Cursed Horizon', 'War of the Worlds', 91529.75, 'Dead Man’s Strait', '1767-02-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (14, 10, 'Dead Man’s Grin', 'Skirmish at Sunset', 76785.62, 'Phantom Shoals', '1689-03-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (15, 6, 'The Storm Serpents', 'Siege of the Stronghold', 69821.22, 'The Cursed Channels', '1608-04-13');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (16, 5, 'The Ashen Blades', 'Rumble in the Jungle', 84910.47, 'Broken Mast Bay', '1706-11-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (17, 8, 'Salty Revenants', 'Showdown at High Noon', 83554.1, 'The Drowned Isles', '1604-05-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (18, 2, 'The Silver Scourge', 'Conquest of the Kingdom', 52908.71, 'Shattered Compass Key', '1689-03-01');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (19, 8, 'Drowned Ghosts', 'Brawl at the Barrens', 8875.9, 'Grimwater Sound', '1629-09-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (20, 4, 'The Voodoo Vultures', 'Duel in the Desert', 2139.21, 'Dead Man’s Strait', '1745-11-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (21, 8, 'Leviathan’s Bane', 'Battle of the Titans', 95172.54, 'Daggerjaw Shoals', '1681-09-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (22, 4, 'Dead Man’s Grin', 'Clash of the Champions', 17500.83, 'Rusted Anchor Haven', '1791-03-04');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (23, 7, 'Grimwater Gang', 'War of the Worlds', 37936.38, 'Hollowwave Gulf', '1736-07-26');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (24, 4, 'The Scarlet Wraiths', 'Skirmish at Sunset', 44254.96, 'The Drowned Isles', '1711-03-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (25, 3, 'The Silver Scourge', 'Siege of the Stronghold', 70610.22, 'Bloodwake Bay', '1668-06-18');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (26, 9, 'Ironfang Buccaneers', 'Rumble in the Jungle', 2040.92, 'Stormwreck Atoll', '1769-11-13');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (27, 2, 'Cursed Horizon', 'Showdown at High Noon', 75350.29, 'Ashen Depths', '1774-08-26');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (28, 2, 'The Storm Serpents', 'Conquest of the Kingdom', 41670.74, 'Ashen Depths', '1751-04-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (29, 2, 'The Voodoo Vultures', 'Brawl at the Barrens', 14390.47, 'Phantom Shoals', '1703-11-25');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (30, 5, 'The Siren’s Howl', 'Duel in the Desert', 45459.7, 'The Drowned Isles', '1784-06-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (31, 8, 'The Broken Compass', 'Battle of the Titans', 68090.86, 'Rusted Anchor Haven', '1612-10-09');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (32, 6, 'The Rusted Cutlasses', 'Clash of the Champions', 30839.34, 'Siren’s Cove', '1789-09-15');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (33, 2, 'The Ashen Blades', 'War of the Worlds', 52366.5, 'Stormwreck Atoll', '1697-11-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (34, 8, 'The Black Tide', 'Skirmish at Sunset', 87634.13, 'Whispering Tides', '1678-12-31');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (35, 6, 'Salty Revenants', 'Siege of the Stronghold', 69170.5, 'Ashen Depths', '1697-08-11');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (36, 1, 'Drowned Ghosts', 'Rumble in the Jungle', 63012.26, 'The Cursed Channels', '1718-03-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (37, 5, 'Crimson Corsairs', 'Showdown at High Noon', 23137.67, 'Blackreef Lagoon', '1680-11-03');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (38, 4, 'Bone Reef Marauders', 'Conquest of the Kingdom', 12407.47, 'Devil’s Backbone Reef', '1761-05-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (39, 5, 'The Daggerfangs', 'Brawl at the Barrens', 67089.52, 'The Cursed Channels', '1653-12-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (40, 3, 'Bloodwake Raiders', 'Duel in the Desert', 10084.75, 'Devil’s Backbone Reef', '1734-12-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (41, 9, 'The Rusted Cutlasses', 'Battle of the Titans', 39823.72, 'Grimwater Sound', '1621-10-28');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (42, 9, 'The Silver Scourge', 'Clash of the Champions', 81598.89, 'Broken Mast Bay', '1669-04-25');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (43, 2, 'Crimson Corsairs', 'War of the Worlds', 93642.86, 'The Cursed Channels', '1657-03-28');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (44, 5, 'Salty Revenants', 'Skirmish at Sunset', 24459.06, 'Bloodwake Bay', '1729-02-08');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (45, 4, 'Bloodwake Raiders', 'Siege of the Stronghold', 23686.72, 'Stormwreck Atoll', '1669-03-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (46, 2, 'The Siren’s Howl', 'Rumble in the Jungle', 53586.49, 'Grimwater Sound', '1695-12-07');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (47, 6, 'Grimwater Gang', 'Showdown at High Noon', 65141.66, 'Skeleton Cove', '1675-12-30');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (48, 1, 'The Storm Serpents', 'Conquest of the Kingdom', 58098.97, 'Whispering Tides', '1675-07-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (49, 7, 'Cursed Horizon', 'Brawl at the Barrens', 24302.05, 'Rusted Anchor Haven', '1747-04-22');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (50, 8, 'Bone Reef Marauders', 'Duel in the Desert', 44426.91, 'Siren’s Cove', '1741-11-26');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (51, 7, 'Leviathan’s Bane', 'Battle of the Titans', 30950.6, 'Broken Mast Bay', '1754-02-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (52, 2, 'The Scarlet Wraiths', 'Clash of the Champions', 11194.43, 'Siren’s Cove', '1799-07-07');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (53, 4, 'The Broken Compass', 'War of the Worlds', 76811.24, 'Leviathan’s Grave', '1616-08-21');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (54, 4, 'Ironfang Buccaneers', 'Skirmish at Sunset', 66001.95, 'Skeleton Cove', '1704-10-31');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (55, 3, 'The Daggerfangs', 'Siege of the Stronghold', 10190.53, 'Leviathan’s Grave', '1761-06-01');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (56, 3, 'The Voodoo Vultures', 'Rumble in the Jungle', 31593.39, 'Skeleton Cove', '1710-04-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (57, 1, 'Dead Man’s Grin', 'Showdown at High Noon', 85881.8, 'Shadowmist Isle', '1701-05-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (58, 3, 'The Black Tide', 'Conquest of the Kingdom', 97492.44, 'Devil’s Backbone Reef', '1627-10-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (59, 5, 'The Ashen Blades', 'Brawl at the Barrens', 83107.87, 'Dead Man’s Strait', '1791-06-01');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (60, 10, 'Drowned Ghosts', 'Duel in the Desert', 13898.01, 'Leviathan’s Grave', '1775-02-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (61, 1, 'The Scarlet Wraiths', 'Battle of the Titans', 16216.65, 'Hollowwave Gulf', '1650-03-11');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (62, 5, 'The Black Tide', 'Clash of the Champions', 91505.54, 'Whispering Tides', '1627-02-07');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (63, 1, 'The Daggerfangs', 'War of the Worlds', 14369.94, 'Shadowmist Isle', '1667-07-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (64, 1, 'Salty Revenants', 'Skirmish at Sunset', 85645.26, 'Devil’s Backbone Reef', '1671-01-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (65, 4, 'Grimwater Gang', 'Siege of the Stronghold', 66184.53, 'Ashen Depths', '1721-08-25');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (66, 9, 'Ironfang Buccaneers', 'Rumble in the Jungle', 51541.04, 'Hollowwave Gulf', '1723-08-30');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (67, 10, 'The Rusted Cutlasses', 'Showdown at High Noon', 39629.1, 'Broken Mast Bay', '1663-07-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (68, 2, 'The Siren’s Howl', 'Conquest of the Kingdom', 56978.88, 'The Cursed Channels', '1612-09-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (69, 6, 'The Broken Compass', 'Brawl at the Barrens', 7730.65, 'Phantom Shoals', '1664-04-11');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (70, 10, 'The Storm Serpents', 'Duel in the Desert', 76591.16, 'Phantom Shoals', '1670-04-11');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (71, 6, 'Bloodwake Raiders', 'Battle of the Titans', 24117.1, 'Hollowwave Gulf', '1613-08-26');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (72, 6, 'Crimson Corsairs', 'Clash of the Champions', 57514.04, 'Daggerjaw Shoals', '1688-11-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (73, 8, 'Dead Man’s Grin', 'War of the Worlds', 67980.17, 'Rusted Anchor Haven', '1681-11-30');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (74, 4, 'Leviathan’s Bane', 'Skirmish at Sunset', 27125.7, 'Grimwater Sound', '1694-03-18');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (75, 7, 'Drowned Ghosts', 'Siege of the Stronghold', 31360.63, 'Siren’s Cove', '1713-07-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (76, 2, 'The Voodoo Vultures', 'Rumble in the Jungle', 39273.27, 'Whispering Tides', '1753-11-12');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (77, 1, 'The Silver Scourge', 'Showdown at High Noon', 84755.22, 'Dead Man’s Strait', '1682-05-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (78, 2, 'Cursed Horizon', 'Conquest of the Kingdom', 91130.38, 'Phantom Shoals', '1799-01-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (79, 7, 'Bone Reef Marauders', 'Brawl at the Barrens', 26645.95, 'Leviathan’s Grave', '1629-06-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (80, 5, 'The Ashen Blades', 'Duel in the Desert', 31378.33, 'Daggerjaw Shoals', '1707-06-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (81, 4, 'The Daggerfangs', 'Battle of the Titans', 35590.5, 'Blackreef Lagoon', '1687-08-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (82, 1, 'Grimwater Gang', 'Clash of the Champions', 78419.14, 'The Drowned Isles', '1680-11-22');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (83, 5, 'The Broken Compass', 'War of the Worlds', 9752.34, 'Ashen Depths', '1716-07-22');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (84, 10, 'Dead Man’s Grin', 'Skirmish at Sunset', 76292.04, 'Dead Man’s Strait', '1641-06-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (85, 7, 'The Storm Serpents', 'Siege of the Stronghold', 84073.83, 'Bloodwake Bay', '1772-04-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (86, 7, 'Drowned Ghosts', 'Rumble in the Jungle', 88550.68, 'Siren’s Cove', '1601-03-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (87, 10, 'Salty Revenants', 'Showdown at High Noon', 78061.64, 'Hollowwave Gulf', '1670-05-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (88, 9, 'Ironfang Buccaneers', 'Conquest of the Kingdom', 11344.87, 'Leviathan’s Grave', '1669-09-07');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (89, 7, 'The Rusted Cutlasses', 'Brawl at the Barrens', 27148.97, 'Whispering Tides', '1795-06-09');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (90, 9, 'The Voodoo Vultures', 'Duel in the Desert', 36236.56, 'Blackreef Lagoon', '1787-01-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (91, 9, 'Bone Reef Marauders', 'Battle of the Titans', 13412.12, 'Grimwater Sound', '1609-04-21');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (92, 2, 'Crimson Corsairs', 'Clash of the Champions', 39144.3, 'Shadowmist Isle', '1607-11-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (93, 5, 'The Siren’s Howl', 'War of the Worlds', 51084.73, 'Shattered Compass Key', '1662-09-04');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (94, 2, 'The Black Tide', 'Skirmish at Sunset', 69504.99, 'Bloodwake Bay', '1742-02-03');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (95, 2, 'The Scarlet Wraiths', 'Siege of the Stronghold', 52559.94, 'Devil’s Backbone Reef', '1731-08-25');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (96, 7, 'The Ashen Blades', 'Rumble in the Jungle', 72483.84, 'Shattered Compass Key', '1756-09-28');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (97, 1, 'The Silver Scourge', 'Showdown at High Noon', 76676.27, 'Blackreef Lagoon', '1720-08-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (98, 8, 'Bloodwake Raiders', 'Conquest of the Kingdom', 51429.28, 'Rusted Anchor Haven', '1791-11-15');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (99, 4, 'Leviathan’s Bane', 'Brawl at the Barrens', 55729.14, 'Stormwreck Atoll', '1703-03-04');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (100, 9, 'Cursed Horizon', 'Duel in the Desert', 20436.21, 'Dead Man’s Strait', '1737-12-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (101, 4, 'The Scarlet Wraiths', 'Battle of the Titans', 90780.58, 'Bloodwake Bay', '1676-10-12');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (102, 3, 'Cursed Horizon', 'Clash of the Champions', 9354.48, 'Devil’s Backbone Reef', '1761-11-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (103, 1, 'Ironfang Buccaneers', 'War of the Worlds', 37860.5, 'Grimwater Sound', '1792-10-08');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (104, 7, 'Bloodwake Raiders', 'Skirmish at Sunset', 22652.81, 'The Cursed Channels', '1703-07-31');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (105, 6, 'Grimwater Gang', 'Siege of the Stronghold', 57934.84, 'Ashen Depths', '1654-11-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (106, 10, 'Leviathan’s Bane', 'Rumble in the Jungle', 67067.7, 'Broken Mast Bay', '1729-01-23');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (107, 9, 'The Storm Serpents', 'Showdown at High Noon', 48243.15, 'Phantom Shoals', '1787-11-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (108, 7, 'The Ashen Blades', 'Conquest of the Kingdom', 20317.14, 'Stormwreck Atoll', '1639-07-26');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (109, 7, 'The Broken Compass', 'Brawl at the Barrens', 31792.82, 'Shattered Compass Key', '1638-01-03');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (110, 10, 'The Voodoo Vultures', 'Duel in the Desert', 26225.03, 'Blackreef Lagoon', '1696-10-11');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (111, 2, 'The Black Tide', 'Battle of the Titans', 59859.97, 'The Drowned Isles', '1692-11-23');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (112, 4, 'The Daggerfangs', 'Clash of the Champions', 90067.3, 'Grimwater Sound', '1646-01-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (113, 10, 'Dead Man’s Grin', 'War of the Worlds', 73205.25, 'Devil’s Backbone Reef', '1682-11-08');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (114, 9, 'The Silver Scourge', 'Skirmish at Sunset', 28707.58, 'Shadowmist Isle', '1759-04-23');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (115, 1, 'Crimson Corsairs', 'Siege of the Stronghold', 79345.61, 'Dead Man’s Strait', '1625-03-18');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (116, 9, 'Bone Reef Marauders', 'Rumble in the Jungle', 67940.44, 'The Cursed Channels', '1780-07-24');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (117, 8, 'Drowned Ghosts', 'Showdown at High Noon', 26708.58, 'Shattered Compass Key', '1615-08-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (118, 5, 'The Rusted Cutlasses', 'Conquest of the Kingdom', 69827.39, 'Grimwater Sound', '1665-07-04');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (119, 7, 'Salty Revenants', 'Brawl at the Barrens', 27034.63, 'Dead Man’s Strait', '1659-03-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (120, 6, 'The Siren’s Howl', 'Duel in the Desert', 73584.39, 'The Drowned Isles', '1655-10-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (121, 1, 'The Storm Serpents', 'Battle of the Titans', 52343.79, 'Daggerjaw Shoals', '1734-05-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (122, 9, 'The Black Tide', 'Clash of the Champions', 98317.59, 'Grimwater Sound', '1737-07-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (123, 2, 'Cursed Horizon', 'War of the Worlds', 80047.66, 'Siren’s Cove', '1727-01-13');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (124, 7, 'The Siren’s Howl', 'Skirmish at Sunset', 59412.34, 'Stormwreck Atoll', '1730-10-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (125, 7, 'The Daggerfangs', 'Siege of the Stronghold', 18934.49, 'Skeleton Cove', '1781-07-04');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (126, 3, 'The Broken Compass', 'Rumble in the Jungle', 90637.1, 'Stormwreck Atoll', '1698-04-24');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (127, 1, 'The Ashen Blades', 'Showdown at High Noon', 63922.68, 'Shadowmist Isle', '1637-02-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (128, 4, 'Grimwater Gang', 'Conquest of the Kingdom', 41984.11, 'Phantom Shoals', '1689-07-21');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (129, 3, 'Bone Reef Marauders', 'Brawl at the Barrens', 4027.37, 'Skeleton Cove', '1794-06-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (130, 5, 'The Silver Scourge', 'Duel in the Desert', 97357.74, 'Whispering Tides', '1699-03-15');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (131, 1, 'Ironfang Buccaneers', 'Battle of the Titans', 28399.09, 'Bloodwake Bay', '1653-01-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (132, 8, 'The Rusted Cutlasses', 'Clash of the Champions', 46918.79, 'Leviathan’s Grave', '1616-08-12');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (133, 2, 'Leviathan’s Bane', 'War of the Worlds', 56226.59, 'Rusted Anchor Haven', '1651-03-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (134, 3, 'Dead Man’s Grin', 'Skirmish at Sunset', 8214.43, 'The Cursed Channels', '1742-01-21');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (135, 4, 'Drowned Ghosts', 'Siege of the Stronghold', 82509.39, 'Shadowmist Isle', '1633-07-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (136, 10, 'Bloodwake Raiders', 'Rumble in the Jungle', 61627.65, 'Skeleton Cove', '1786-10-30');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (137, 7, 'The Scarlet Wraiths', 'Showdown at High Noon', 87527.4, 'Rusted Anchor Haven', '1676-01-09');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (138, 10, 'The Voodoo Vultures', 'Conquest of the Kingdom', 8639.69, 'Leviathan’s Grave', '1673-07-09');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (139, 4, 'Crimson Corsairs', 'Brawl at the Barrens', 56036.41, 'Dead Man’s Strait', '1676-08-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (140, 2, 'Salty Revenants', 'Duel in the Desert', 36931.36, 'Phantom Shoals', '1657-01-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (141, 2, 'The Broken Compass', 'Battle of the Titans', 46026.74, 'Broken Mast Bay', '1635-06-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (142, 4, 'Dead Man’s Grin', 'Clash of the Champions', 24082.98, 'Hollowwave Gulf', '1629-01-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (143, 9, 'Grimwater Gang', 'War of the Worlds', 48673.97, 'Bloodwake Bay', '1670-04-23');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (144, 2, 'Cursed Horizon', 'Skirmish at Sunset', 79180.66, 'Blackreef Lagoon', '1796-04-13');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (145, 1, 'Leviathan’s Bane', 'Siege of the Stronghold', 90677.72, 'Hollowwave Gulf', '1702-04-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (146, 5, 'Salty Revenants', 'Rumble in the Jungle', 97387.58, 'Broken Mast Bay', '1674-06-07');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (147, 5, 'The Daggerfangs', 'Showdown at High Noon', 61435.17, 'Whispering Tides', '1743-06-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (148, 2, 'The Scarlet Wraiths', 'Conquest of the Kingdom', 6577.61, 'Ashen Depths', '1771-08-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (149, 9, 'Bloodwake Raiders', 'Brawl at the Barrens', 33261.35, 'Daggerjaw Shoals', '1777-06-11');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (150, 3, 'The Voodoo Vultures', 'Duel in the Desert', 10438.56, 'Devil’s Backbone Reef', '1665-07-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (151, 7, 'The Storm Serpents', 'Battle of the Titans', 27509.65, 'Hollowwave Gulf', '1744-06-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (152, 10, 'The Siren’s Howl', 'Clash of the Champions', 77030.22, 'Rusted Anchor Haven', '1780-11-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (153, 2, 'Ironfang Buccaneers', 'War of the Worlds', 77780.37, 'Hollowwave Gulf', '1795-01-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (154, 2, 'Crimson Corsairs', 'Skirmish at Sunset', 31835.89, 'Skeleton Cove', '1713-04-01');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (155, 5, 'The Ashen Blades', 'Siege of the Stronghold', 93685.82, 'Grimwater Sound', '1602-08-27');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (156, 2, 'The Silver Scourge', 'Rumble in the Jungle', 15601.86, 'Shattered Compass Key', '1751-10-26');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (157, 4, 'The Rusted Cutlasses', 'Showdown at High Noon', 62890.14, 'Ashen Depths', '1726-11-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (158, 8, 'Bone Reef Marauders', 'Conquest of the Kingdom', 58587.83, 'Blackreef Lagoon', '1735-03-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (159, 7, 'Drowned Ghosts', 'Brawl at the Barrens', 38444.23, 'Devil’s Backbone Reef', '1623-01-24');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (160, 8, 'The Black Tide', 'Duel in the Desert', 65221.91, 'Siren’s Cove', '1626-01-18');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (161, 7, 'Bloodwake Raiders', 'Battle of the Titans', 1947.77, 'Broken Mast Bay', '1600-09-01');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (162, 10, 'Salty Revenants', 'Clash of the Champions', 27598.71, 'Stormwreck Atoll', '1698-05-01');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (163, 9, 'The Silver Scourge', 'War of the Worlds', 67013.91, 'Leviathan’s Grave', '1773-10-29');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (164, 5, 'Grimwater Gang', 'Skirmish at Sunset', 43677.04, 'Ashen Depths', '1691-03-21');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (165, 9, 'The Siren’s Howl', 'Siege of the Stronghold', 94864.39, 'Siren’s Cove', '1674-03-13');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (166, 3, 'The Voodoo Vultures', 'Rumble in the Jungle', 37514.0, 'Whispering Tides', '1680-11-17');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (167, 7, 'The Ashen Blades', 'Showdown at High Noon', 6260.2, 'Shadowmist Isle', '1606-07-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (168, 4, 'Ironfang Buccaneers', 'Conquest of the Kingdom', 70884.96, 'Rusted Anchor Haven', '1606-04-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (169, 10, 'Leviathan’s Bane', 'Brawl at the Barrens', 27682.43, 'Skeleton Cove', '1693-05-25');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (170, 4, 'The Rusted Cutlasses', 'Duel in the Desert', 21092.59, 'The Drowned Isles', '1681-11-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (171, 7, 'The Black Tide', 'Battle of the Titans', 94508.26, 'Bloodwake Bay', '1601-01-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (172, 8, 'Cursed Horizon', 'Clash of the Champions', 74011.65, 'Leviathan’s Grave', '1795-10-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (173, 4, 'Crimson Corsairs', 'War of the Worlds', 52302.34, 'Broken Mast Bay', '1632-12-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (174, 10, 'The Scarlet Wraiths', 'Skirmish at Sunset', 47442.63, 'Shattered Compass Key', '1709-05-23');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (175, 5, 'Bone Reef Marauders', 'Siege of the Stronghold', 40182.45, 'The Cursed Channels', '1661-10-09');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (176, 10, 'The Broken Compass', 'Rumble in the Jungle', 86526.26, 'The Drowned Isles', '1748-05-30');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (177, 9, 'Dead Man’s Grin', 'Showdown at High Noon', 94986.89, 'Ashen Depths', '1610-05-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (178, 4, 'The Daggerfangs', 'Conquest of the Kingdom', 44793.57, 'Daggerjaw Shoals', '1643-10-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (179, 6, 'The Storm Serpents', 'Brawl at the Barrens', 31273.73, 'Daggerjaw Shoals', '1742-01-16');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (180, 3, 'Drowned Ghosts', 'Duel in the Desert', 27940.53, 'Whispering Tides', '1604-08-13');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (181, 2, 'The Scarlet Wraiths', 'Battle of the Titans', 94018.08, 'Dead Man’s Strait', '1672-12-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (182, 7, 'Drowned Ghosts', 'Clash of the Champions', 28456.74, 'Siren’s Cove', '1770-08-31');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (183, 4, 'Crimson Corsairs', 'War of the Worlds', 72621.64, 'Devil’s Backbone Reef', '1664-09-03');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (184, 7, 'The Silver Scourge', 'Skirmish at Sunset', 45721.49, 'Blackreef Lagoon', '1794-06-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (185, 2, 'The Voodoo Vultures', 'Siege of the Stronghold', 33288.59, 'Whispering Tides', '1785-11-28');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (186, 2, 'Bloodwake Raiders', 'Rumble in the Jungle', 86538.37, 'Bloodwake Bay', '1796-06-02');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (187, 3, 'Leviathan’s Bane', 'Showdown at High Noon', 97338.19, 'Leviathan’s Grave', '1624-11-04');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (188, 8, 'Salty Revenants', 'Conquest of the Kingdom', 57861.46, 'The Drowned Isles', '1603-05-07');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (189, 9, 'Dead Man’s Grin', 'Brawl at the Barrens', 12122.49, 'Phantom Shoals', '1637-03-14');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (190, 2, 'The Storm Serpents', 'Duel in the Desert', 30114.02, 'Siren’s Cove', '1659-04-08');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (191, 9, 'Grimwater Gang', 'Battle of the Titans', 10704.66, 'The Cursed Channels', '1785-03-19');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (192, 1, 'The Broken Compass', 'Clash of the Champions', 47142.14, 'Shattered Compass Key', '1797-02-23');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (193, 8, 'The Rusted Cutlasses', 'War of the Worlds', 89062.62, 'Phantom Shoals', '1604-08-09');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (194, 7, 'Bone Reef Marauders', 'Skirmish at Sunset', 48840.71, 'Stormwreck Atoll', '1605-11-08');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (195, 1, 'Cursed Horizon', 'Siege of the Stronghold', 62805.61, 'Blackreef Lagoon', '1739-10-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (196, 7, 'The Black Tide', 'Rumble in the Jungle', 62231.0, 'Shadowmist Isle', '1718-08-20');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (197, 10, 'The Daggerfangs', 'Showdown at High Noon', 28682.31, 'Phantom Shoals', '1745-12-06');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (198, 1, 'The Siren’s Howl', 'Conquest of the Kingdom', 39417.85, 'Daggerjaw Shoals', '1653-09-05');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (199, 5, 'Ironfang Buccaneers', 'Brawl at the Barrens', 72407.07, 'Whispering Tides', '1722-05-10');
insert into battle (Bid, Casualties, Winner, Name, LootAmount, Location, Date) values (200, 10, 'The Ashen Blades', 'Duel in the Desert', 66143.25, 'Grimwater Sound', '1780-03-04');
