insert into crew (Cid, Name, Location) values (1, 'The Black Tide', 'Bloodwake Bay');
insert into crew (Cid, Name, Location) values (2, 'Crimson Corsairs', 'Siren’s Cove');
insert into crew (Cid, Name, Location) values (3, 'The Daggerfangs', 'Dead Man’s Strait');
insert into crew (Cid, Name, Location) values (4, 'Bone Reef Marauders', 'Blackreef Lagoon');
insert into crew (Cid, Name, Location) values (5, 'The Storm Serpents', 'Leviathan’s Grave');
insert into crew (Cid, Name, Location) values (6, 'Ironfang Buccaneers', 'Whispering Tides');
insert into crew (Cid, Name, Location) values (7, 'The Scarlet Wraiths', 'Daggerjaw Shoals');
insert into crew (Cid, Name, Location) values (8, 'Drowned Ghosts', 'The Drowned Isles');
insert into crew (Cid, Name, Location) values (9, 'The Siren’s Howl', 'Stormwreck Atoll');
insert into crew (Cid, Name, Location) values (10, 'Bloodwake Raiders', 'Broken Mast Bay');
insert into crew (Cid, Name, Location) values (11, 'The Ashen Blades', 'Grimwater Sound');
insert into crew (Cid, Name, Location) values (12, 'Leviathan’s Bane', 'Devil’s Backbone Reef');
insert into crew (Cid, Name, Location) values (13, 'The Rusted Cutlasses', 'Rusted Anchor Haven');
insert into crew (Cid, Name, Location) values (14, 'Grimwater Gang', 'Phantom Shoals');
insert into crew (Cid, Name, Location) values (15, 'The Broken Compass', 'Hollowwave Gulf');
insert into crew (Cid, Name, Location) values (16, 'Cursed Horizon', 'The Cursed Channels');
insert into crew (Cid, Name, Location) values (17, 'The Silver Scourge', 'Ashen Depths');
insert into crew (Cid, Name, Location) values (18, 'Dead Man’s Grin', 'Shattered Compass Key');
insert into crew (Cid, Name, Location) values (19, 'The Voodoo Vultures', 'Skeleton Cove');
insert into crew (Cid, Name, Location) values (20, 'Salty Revenants', 'Shadowmist Isle');
