insert into ship (Sid, Name, Type, Cid) values (1, 'Leviathan’s Grave', 'Frigate', '1');
insert into ship (Sid, Name, Type, Cid) values (2, 'Phantom’s Wake', 'Sloop', '2');
insert into ship (Sid, Name, Type, Cid) values (3, 'The Rotten Crown', 'Brigantine', '3');
insert into ship (Sid, Name, Type, Cid) values (4, 'Red Leviathan', 'Galleon', '4');
insert into ship (Sid, Name, Type, Cid) values (5, 'Tempest Serpent', 'Barque', '5');
insert into ship (Sid, Name, Type, Cid) values (6, 'Shipbreaker’s Promise', 'Brigantine', '6');
insert into ship (Sid, Name, Type, Cid) values (7, 'Frostfang', 'Sloop', '7');
insert into ship (Sid, Name, Type, Cid) values (8, 'Hollow Warden', 'Galleon', '8');
insert into ship (Sid, Name, Type, Cid) values (9, 'The Coral Phantom', 'Barque', '9');
insert into ship (Sid, Name, Type, Cid) values (10, 'The Blighted Jewel', 'Barque', '10');
insert into ship (Sid, Name, Type, Cid) values (11, 'Driftwood Phantom', 'Frigate', '11');
insert into ship (Sid, Name, Type, Cid) values (12, 'Deepstar Marauder', 'Galleon', '12');
insert into ship (Sid, Name, Type, Cid) values (13, 'Rustfang', 'Barque', '13');
insert into ship (Sid, Name, Type, Cid) values (14, 'Siren’s Teeth', 'Frigate', '14');
insert into ship (Sid, Name, Type, Cid) values (15, 'Broken Compass', 'Brigantine', '15');
insert into ship (Sid, Name, Type, Cid) values (16, 'Pale Leviathan', 'Galleon', '16');
insert into ship (Sid, Name, Type, Cid) values (17, 'Leviathan’s Howl', 'Brigantine', '17');
insert into ship (Sid, Name, Type, Cid) values (18, 'Riptide Raider', 'Brigantine', '18');
insert into ship (Sid, Name, Type, Cid) values (19, 'The Sunken Star', 'Brigantine', '19');
insert into ship (Sid, Name, Type, Cid) values (20, 'Rustfang', 'Brigantine', '20');
insert into ship (Sid, Name, Type, Cid) values (21, 'Cursed Riptide', 'Barque', '1');
insert into ship (Sid, Name, Type, Cid) values (22, 'Riptide Raider', 'Frigate', '2');
insert into ship (Sid, Name, Type, Cid) values (23, 'Ghostwake', 'Frigate', '3');
insert into ship (Sid, Name, Type, Cid) values (24, 'Leviathan’s Roar', 'Sloop', '4');
insert into ship (Sid, Name, Type, Cid) values (25, 'Rustscale Raider', 'Sloop', '5');
insert into ship (Sid, Name, Type, Cid) values (26, 'Burning Marlin', 'Brigantine', '6');
insert into ship (Sid, Name, Type, Cid) values (27, 'Voodoo Pearl', 'Barque', '7');
insert into ship (Sid, Name, Type, Cid) values (28, 'Broken Trident', 'Sloop', '8');
insert into ship (Sid, Name, Type, Cid) values (29, 'Wraithfin', 'Galleon', '9');
insert into ship (Sid, Name, Type, Cid) values (30, 'Silent Torrent', 'Brigantine', '10');
insert into ship (Sid, Name, Type, Cid) values (31, 'Moonfang Raider', 'Galleon', '11');
insert into ship (Sid, Name, Type, Cid) values (32, 'Devil’s Mistress', 'Brigantine', '12');
insert into ship (Sid, Name, Type, Cid) values (33, 'Seafoam Marauder', 'Galleon', '13');
insert into ship (Sid, Name, Type, Cid) values (34, 'Gallows Light', 'Sloop', '14');
insert into ship (Sid, Name, Type, Cid) values (35, 'Shadeclaw Raider', 'Brigantine', '15');
insert into ship (Sid, Name, Type, Cid) values (36, 'The Scarlet Sinker', 'Barque', '16');
insert into ship (Sid, Name, Type, Cid) values (37, 'Frostfang', 'Brigantine', '17');
insert into ship (Sid, Name, Type, Cid) values (38, 'The Drowned Maiden', 'Barque', '18');
insert into ship (Sid, Name, Type, Cid) values (39, 'Drowned Dreamer', 'Frigate', '19');
insert into ship (Sid, Name, Type, Cid) values (40, 'Blackblood Mariner', 'Sloop', '20');
insert into ship (Sid, Name, Type, Cid) values (41, 'Phantom’s Oath', 'Sloop', '1');
insert into ship (Sid, Name, Type, Cid) values (42, 'Marrow''s End', 'Frigate', '2');
insert into ship (Sid, Name, Type, Cid) values (43, 'Starless Phantom', 'Frigate', '3');
insert into ship (Sid, Name, Type, Cid) values (44, 'Drowned Dreamer', 'Barque', '4');
insert into ship (Sid, Name, Type, Cid) values (45, 'Salted Doom', 'Brigantine', '5');
insert into ship (Sid, Name, Type, Cid) values (46, 'Starlit Marauder', 'Frigate', '6');
insert into ship (Sid, Name, Type, Cid) values (47, 'The Ebon Drake', 'Brigantine', '7');
insert into ship (Sid, Name, Type, Cid) values (48, 'Cursed Skull', 'Barque', '8');
insert into ship (Sid, Name, Type, Cid) values (49, 'Shadebreaker', 'Barque', '9');
insert into ship (Sid, Name, Type, Cid) values (50, 'The Shattered Wave', 'Sloop', '10');
insert into ship (Sid, Name, Type, Cid) values (51, 'Broken Trident', 'Brigantine', '11');
insert into ship (Sid, Name, Type, Cid) values (52, 'Cracked Skull', 'Barque', '12');
insert into ship (Sid, Name, Type, Cid) values (53, 'Broken Lantern', 'Barque', '13');
insert into ship (Sid, Name, Type, Cid) values (54, 'Black Sail’s Oath', 'Frigate', '14');
insert into ship (Sid, Name, Type, Cid) values (55, 'Bloodwake Marauder', 'Barque', '15');
insert into ship (Sid, Name, Type, Cid) values (56, 'Wretched Corsair', 'Brigantine', '16');
insert into ship (Sid, Name, Type, Cid) values (57, 'Hollow Warden', 'Frigate', '17');
insert into ship (Sid, Name, Type, Cid) values (58, 'The Scarlet Sinker', 'Frigate', '18');
insert into ship (Sid, Name, Type, Cid) values (59, 'Broken Trident', 'Sloop', '19');
insert into ship (Sid, Name, Type, Cid) values (60, 'The Ebon Drake', 'Galleon', '20');
insert into ship (Sid, Name, Type, Cid) values (61, 'Gallows Anchor', 'Frigate', '1');
insert into ship (Sid, Name, Type, Cid) values (62, 'Saltblood', 'Galleon', '2');
insert into ship (Sid, Name, Type, Cid) values (63, 'Rotfin Corsair', 'Frigate', '3');
insert into ship (Sid, Name, Type, Cid) values (64, 'Deepstar Marauder', 'Galleon', '4');
insert into ship (Sid, Name, Type, Cid) values (65, 'Kraken''s Doom', 'Barque', '5');
insert into ship (Sid, Name, Type, Cid) values (66, 'The Silent Dagger', 'Barque', '6');
insert into ship (Sid, Name, Type, Cid) values (67, 'Abysswalker', 'Frigate', '7');
insert into ship (Sid, Name, Type, Cid) values (68, 'The Shrieking Siren', 'Barque', '8');
insert into ship (Sid, Name, Type, Cid) values (69, 'Cursed Skull', 'Sloop', '9');
insert into ship (Sid, Name, Type, Cid) values (70, 'Death''s Embrace', 'Galleon', '10');
insert into ship (Sid, Name, Type, Cid) values (71, 'Vulture’s Grin', 'Brigantine', '11');
insert into ship (Sid, Name, Type, Cid) values (72, 'Hollowwake Warden.', 'Barque', '12');
insert into ship (Sid, Name, Type, Cid) values (73, 'Sea Phantom', 'Brigantine', '13');
insert into ship (Sid, Name, Type, Cid) values (74, 'Pale Shark', 'Frigate', '14');
insert into ship (Sid, Name, Type, Cid) values (75, 'Stormborn Revenant', 'Frigate', '15');
insert into ship (Sid, Name, Type, Cid) values (76, 'Bone Ripper', 'Barque', '16');
insert into ship (Sid, Name, Type, Cid) values (77, 'Brinewolf', 'Galleon', '17');
insert into ship (Sid, Name, Type, Cid) values (78, 'Thundertide', 'Sloop', '18');
insert into ship (Sid, Name, Type, Cid) values (79, 'Widow’s Fang', 'Barque', '19');
insert into ship (Sid, Name, Type, Cid) values (80, 'The Grim Albatross', 'Sloop', '20');
insert into ship (Sid, Name, Type, Cid) values (81, 'Deadstar Corsair', 'Brigantine', '1');
insert into ship (Sid, Name, Type, Cid) values (82, 'Voodoo Pearl', 'Galleon', '2');
insert into ship (Sid, Name, Type, Cid) values (83, 'Phantom’s Wake', 'Barque', '3');
insert into ship (Sid, Name, Type, Cid) values (84, 'Drowned Wraith', 'Galleon', '4');
insert into ship (Sid, Name, Type, Cid) values (85, 'Scourgewind', 'Galleon', '5');
insert into ship (Sid, Name, Type, Cid) values (86, 'Darkwater Serpent', 'Galleon', '6');
insert into ship (Sid, Name, Type, Cid) values (87, 'Drowned Wraith', 'Brigantine', '7');
insert into ship (Sid, Name, Type, Cid) values (88, 'Thundercaller', 'Galleon', '8');
insert into ship (Sid, Name, Type, Cid) values (89, 'Deadwave Brig', 'Galleon', '9');
insert into ship (Sid, Name, Type, Cid) values (90, 'Wailing Horizon', 'Sloop', '10');
insert into ship (Sid, Name, Type, Cid) values (91, 'The Scarlet Sinker', 'Sloop', '11');
insert into ship (Sid, Name, Type, Cid) values (92, 'The Bleeding Horizon', 'Galleon', '12');
insert into ship (Sid, Name, Type, Cid) values (93, 'The Silent Dagger', 'Brigantine', '13');
insert into ship (Sid, Name, Type, Cid) values (94, 'Saltblood', 'Galleon', '14');
insert into ship (Sid, Name, Type, Cid) values (95, 'Bitter Current', 'Sloop', '15');
insert into ship (Sid, Name, Type, Cid) values (96, 'Iron Blood', 'Brigantine', '16');
insert into ship (Sid, Name, Type, Cid) values (97, 'The Scarlet Tempest', 'Brigantine', '17');
insert into ship (Sid, Name, Type, Cid) values (98, 'Drowned Wraith', 'Barque', '18');
insert into ship (Sid, Name, Type, Cid) values (99, 'The Scarlet Tempest', 'Frigate', '19');
insert into ship (Sid, Name, Type, Cid) values (100, 'Brinewolf', 'Sloop', '20');
